Feat/ab#61944 abc implement breadcrumbs component
ReliefApplications/ems-frontend pull request #1270
Opened 2023-04-18 07:06 UTC by Bricecrx

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Ticket

Please insert link to ticket

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Sreenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-18 08:39 UTC, unai-reliefapp requested changes

2023-04-18 08:39 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
> +export enum BreadcrumbDisplay {
Please move the enums or interfaces to a separate folder named enums or interface in the breadcrumbs folder, depends the case and export them in the `index.ts` file as explained in the `README` so we can access those outside the lib if needed without the need of importing the whole component

2023-04-18 08:39 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
> +import { moduleMetadata, Story, Meta } from '@storybook/angular';
As we are creating a new component, let's try to keep a correct syntax for the naming, please correct the sep**e**rator to sep**a**rator

2023-04-18 08:39 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
> +          *ngIf="!(path.indexOf(pth, 0) === 0)"
More easy way to do it without so much logic involved is to use the Angular built in logic to see if the element is last or first: https://angular.io/api/common/NgForOf#local-variables

For example
`<li *ngFor="pth of path; let last as last" class="flex>`

And you can place the svg after the `<a>` element in all cases and show it only if `!last`

2023-04-18 08:39 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
> +<nav
Please give it a second thought and try to not duplicate so much html code, workaround with different classes but try to keep the html structure as simple as possible.

For example to use one separator or another you can use the ng-template element and you dont have to worry where to place those:
https://www.tektutorialshub.com/angular/ng-template-in-angular/

KR, Unai

2023-04-18 08:39 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
> +Primary.args = {
Please check how cases are provided in the stories:
https://github.com/ReliefApplications/oort-frontend/pull/1269/files#diff-fe72179fde370ba2f9cff113c38a25b3ac8b383f0d2c731719effa2f088b089b
And add one case per type of breadcrumb case

Thanks

2023-04-18 10:29 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.ts
> +export enum BreadcrumbDisplay {
Don't forget to export those in the `index.ts` file to use them outside the UI library!

2023-04-18 10:32 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
Why contained and full display modes cannot use slash separator?
Out of curiosity, i didnt find any guide about that.

KR, Unai

2023-04-18 13:58 UTC, Bricecrx commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
Because it uses icon from certain shapes and there is only chevron icons. 
Moreover, it is as defined in the ticket

2023-04-18 14:25 UTC, unai-reliefapp requested changes

2023-04-18 14:25 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.module.ts
> +  imports: [CommonModule],
In order to export anything from the NgModule you have to add it to the `exports` property as an array 😸 In this case you'll have to add:
`exports: [BreadcrumbsComponent]` below the imports

Info: https://angular.io/api/core/NgModule#exports

2023-04-18 14:25 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.stories.ts
True @Bricecrx , it only applies to the simple, but is not specified which is the default separator for the other cases, the chevron or the slash.

Address the other issues and we'll wait until @AntoineRelief feedback

Thanks,
KR, Unai

2023-04-18 14:25 UTC, unai-reliefapp commented on libs/ui/src/index.ts
> +import { from } from 'rxjs';
We have an infiltrated here
👀 
this import should be gone

2023-04-18 14:25 UTC, unai-reliefapp commented on libs/ui/src/lib/breadcrumbs/breadcrumbs.component.html
> +              *ngIf="!f"
Much much better @Bricecrx , thanks
As we arrived so far, let's improve a couple of more things here to create a stunning breadcrum html 😉 

- The first ngClass in here:
Applies `flex` class for all types, so we can delete all conditions instead of the one for `FULL`, as this:

```
[ngClass]="{
   'border-b border-gray-200 bg-white': display === BreadcrumbsTypes.FULL
  }"
```
Would you agree?

- ngSwitch is a good solve for the different template rendering, but you see that the ngSwitch is inside the ngFor, so the ngSwitch would check what to render for each rendered breadcrumb item, which is a no needed performance loss(breadcrumb is never going to be very long but still). Please try to render the needed template using ngSwitch as you did but do the check outside the ngFor template and render the resolved template inside the ngFor template instead.

- The `*ngIf="!f"` is placed in each one of the template types, which means that no matter what template type we display, that condition should be checked. ¿Wouldn't be better to do that check a level up and do it just once and write it once instead of doing it in each of the template types?

- Finally, even if we are not checking the separator type for the other types(`FULL` and `CONTAINED`), try not to repeat the default separators for them and reuse the one that you already create for the chevron!!

Thanks, good luck!

2023-04-20 07:01 UTC, unai-reliefapp approved these changes

2023-04-20 07:02 UTC, unai-reliefapp commented
@AntoineRelief  This one looks good to me 👍
I'll keep all without merging them until you give a double check for the first ones
KR, Unai

2023-04-20 15:59 UTC, AntoineRelief commented on libs/ui/src/lib/breadcrumbs/enums/breadcrumb-display.enum.ts
> +export enum BreadcrumbDisplay {
@unai-reliefapp @Bricecrx be aware with the enums to always use string values, otherwise, the value is the index in the enum by default
which would not make any sense when using the component in another component, as it would look like that:
<ui-breadcrumbs [display]="0"></ui-breadcrumbs>

2023-04-20 16:00 UTC, merged