feat/AB#62243 creating branch, empty component and stories
ReliefApplications/ems-frontend pull request #1284
Opened 2023-04-24 06:32 UTC by Bricecrx

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Ticket

Please insert link to ticket

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Sreenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-24 14:53 UTC, unai-reliefapp requested changes

2023-04-24 14:53 UTC, unai-reliefapp commented on libs/ui/src/lib/toolbar/toolbar.component.html
Check the whole structure of the toolbar, the text within for example currently is an `<h1>` and not `h2` as you place there:
![image](https://user-images.githubusercontent.com/123092672/234031388-f0724f40-aebb-484d-a854-f46d00b116bf.png)


Also our current text does not have weight, and this one has, which is wrong:
![image](https://user-images.githubusercontent.com/123092672/234031737-3f99a7c2-2522-470f-aa8c-032843b55881.png)

Please check how our header is behaving on small screen sizes, same behavior should be followed:
![image](https://user-images.githubusercontent.com/123092672/234032067-6c26f56b-73e7-4686-acdf-952fdac352aa.png)

2023-04-24 14:53 UTC, unai-reliefapp commented on libs/ui/src/lib/toolbar/toolbar.component.stories.ts
> +  <button
@Bricecrx If possible please use two icons for the `rightContent` instead of those random content buttons to have a more precise testing regarding that part of the heading.

![image](https://user-images.githubusercontent.com/123092672/234033928-c6a7a951-7761-4a33-9ebf-42444e22aa40.png)

Thank you

2023-04-25 11:18 UTC, AntoineRelief commented on libs/ui/src/lib/toolbar/toolbar.component.scss
> +    @apply text-2xl leading-7 whitespace-nowrap text-clip;
@Bricecrx 
when you can avoid to use @apply, you should not use it
there, you can directly put it in the html
I think this is valid for all items of this list

2023-04-25 11:19 UTC, Bricecrx commented on libs/ui/src/lib/toolbar/toolbar.component.scss
> +    @apply text-2xl leading-7 whitespace-nowrap text-clip;
Ok, I'll pay attention

2023-05-08 17:42 UTC, AntoineRelief commented
I should have detected it sooner, I don't think implementation of the component would bring much as part of the UI library
Sorry that you spent time on that

2023-05-08 17:42 UTC, closed without merging

2023-05-08 17:43 UTC, AntoineRelief commented
A simpler component, just for the header would do the job