feat/AB#62230-implement-autocomplete
ReliefApplications/ems-frontend pull request #1293
Opened 2023-04-25 19:47 UTC by estelafs

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Ticket
[ABC- Implement Autocomplete component](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/62230)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Sreenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-04-27 09:37 UTC, unai-reliefapp requested changes

2023-04-27 09:37 UTC, unai-reliefapp commented on libs/ui/src/lib/autocomplete/autocomplete.component.stories.ts
> +      <form [formGroup]="formGroup">
Please double check how the material automplete is implemented:
![image](https://user-images.githubusercontent.com/123092672/234817395-df41619a-568f-49b6-b451-696e84714443.png)
It's using a directive to link the autocomplete list to the needed input. Please follow the same guide, so we can inject the autocomplete list to any input, regarding of it's styling and methods.

You have an example of how we link a directive to another element in here: https://github.com/ReliefApplications/oort-frontend/pull/1293/files#diff-c26d4768141d7e983db754afbf3197d002fe16cc3704d9fdecdd430d406724ad
The directive used: https://github.com/ReliefApplications/oort-frontend/blob/feat/AB%2361955_ABC-implement-flyout-menu-component/libs/ui/src/lib/menu/menu.directive.ts

2023-04-27 09:37 UTC, unai-reliefapp commented on libs/ui/src/lib/autocomplete/autocomplete.component.html
> +    [ngClass]="{
For the hover effect on option background please use the `bg-primary`


Thanks

2023-04-27 09:37 UTC, unai-reliefapp commented on libs/ui/src/lib/autocomplete/autocomplete.component.ts
Please double check the selection check logic:
![image](https://user-images.githubusercontent.com/123092672/234822443-a1612286-e422-46e5-99a3-4622d216a539.png)
![image](https://user-images.githubusercontent.com/123092672/234822758-58ca6498-5571-41ec-82d7-b1d6860307b9.png)

2023-04-28 19:58 UTC, estelafs commented
@unai-reliefapp I updated the PR with the requested changes (in the end the component was not needed, only the directive). Please take a look and let me know if anything is wrong

2023-05-03 08:39 UTC, unai-reliefapp commented
> @unai-reliefapp I updated the PR with the requested changes (in the end the component was not needed, only the directive). Please take a look and let me know if anything is wrong

Hi @estelafs , I updated the PR with some changes regarding DOM manipulation using Renderer2 in Angular, that's the correct way of doing it: https://angular.io/api/core/Renderer2

Besides that, two notes:

- with the current implementation what happens if want to access the options children and the accessor is different than `children`, as here for example?

![image](https://user-images.githubusercontent.com/123092672/235866891-cbe62d5f-9a85-4430-899e-b7cb8bd463ed.png)
Are we going to map all the options given to the directive so they follow the AutocompleteItem interface?

- If there is an icon involved in each item of the autocomplete list as here?

![image](https://user-images.githubusercontent.com/123092672/235867420-1753e97a-ea8c-470f-9f9a-1becd1e2278a.png)

The use of a component to handle the option projection was in order to take care of these two points mainly,

Also please look that we are using a custom function input to tell the autocomplete how we want to display the items in the list, as here: https://github.com/ReliefApplications/oort-frontend/blob/tailwind/libs/safe/src/lib/components/ui/tagbox/tagbox.component.html#L40
Please make sure that we can add a custom display to the list items as well if needed

Thanks, any doubt please write me back

2023-05-26 07:20 UTC, merged