fix/survey-questions-readonly
ReliefApplications/ems-frontend pull request #1648
Opened 2023-07-18 20:06 UTC by estelafs

# Description
Question isReadyOnly propriety never working, even if on a page without any logic configurations. Read only for questions only working when page also was in a read-only state
The issue didn't exist in the test survey but in the add a new record, update record, and update record in the grid modal

## Type of change
- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Creating questions that assume the readOnly state at different times and seeing them behave as they should.

## Screenshots
![ro-add](https://github.com/ReliefApplications/oort-frontend/assets/28535394/f8b29db3-3ae9-47b5-aef2-72b91096ddb0)

![ro-grid](https://github.com/ReliefApplications/oort-frontend/assets/28535394/14b07aa8-fd16-4c1c-9f57-49e534827540)

# Checklist:

( * == Mandatory ) 

- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-02 06:24 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form/form.component.ts
> +      if (field.readOnly) {
Hi @estelafs , could happen that the question has readOnly state on and field not? In that case the false value wont be assigned, and also, readOnly property is always in the field, or only for the cases where is true? in order to take care of both values of readOnly i'll recommend to replace forEach content with this

```
      if ('readOnly' in field) {
      this.survey.getQuestionByName(field.name).readOnly = field.readOnly;
      }else{
      this.survey.getQuestionByName(field.name).readOnly = false;
      }
```
To cover all edge cases and dont leaving any loose case.

KR, Unai

2023-08-02 06:27 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form-modal/form-modal.component.ts
> +            question?.readOnly ?? false;
```suggestion
            question.readOnly ?? false;
```

2023-08-02 06:29 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form-modal/form-modal.component.ts
> +      elements?.forEach((question: any) => {
```suggestion
      elements.forEach((question: any) => {
```
You are already checking if elements exists before calling initReadOnly question, no need for duplicated checks 😜

2023-08-02 06:30 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form-modal/form-modal.component.ts
> +      initReadOnly(page.elements);
```suggestion
    if (page.elements) {
      initReadOnly(page.elements);
    }
```

2023-08-02 06:32 UTC, unai-reliefapp requested changes
Just the comments I left, not critical, but this little PRs are perfect to train our attention to little details where the devil lives

2023-08-03 12:50 UTC, unai-reliefapp approved these changes

2023-08-07 14:39 UTC, AntoineRelief commented
@estelafs 

cc @unai-reliefapp 

I need to close this one, as it would not work:
- during addition, all fields should be editable ( if visible to the user ). It's a requirement from WHO. If we want to be more specific, and prevent that, we would need to add more options to surveyjs
- the logic would override some other logic we do in one of the methods of form-builder service. Indeed, depending on the permissions you have, some of the fields would be hidden / not editable. The code there would set as editable all fields that are still visible to the user, and could have been set as non editable by the createSurvey method of the service

2023-08-07 14:39 UTC, closed without merging