Fix/ab#69615 last modified displaying wrong data
ReliefApplications/ems-frontend pull request #1665
Opened 2023-07-26 20:13 UTC by RenzoPrats

# Description

In quick action buttons if the options "Pre-fill form with selected data" or "Attach to record" is selected and we also select "Auto-modify selected rows" when the button for the action is clicked even if the open modal is canceled the "Auto-modify selected rows" was happening, so now it only will happen when it's concluded the "Pre-fill form with selected data" or "Attach to record". Also modified the order of the options steps according to the comment below.

## Ticket

https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69615

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

It has been tested verifying in the application if now the  "Auto-modify selected rows" only happen when it's concluded the "Pre-fill form with selected data" or "Attach to record".

## Screenshots

![Peek 26-07-2023 17-03](https://github.com/ReliefApplications/oort-frontend/assets/56398308/b8a7ece0-df90-40b5-88b9-d92b1d069e9e)

# Checklist:

( * == Mandatory ) 

- [X] * The pull request is linked to an existing milestone
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-07-27 10:57 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/grid/grid.component.ts
> +              this.promisedRowsModifications(
Hi @RenzoPrats , why do we not wait to the row modification rows promise to end in order to trigger the reloadData method of the grid?

2023-07-27 10:58 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/grid/grid.component.ts
> +                                  this.promisedRowsModifications(
Same as the previous comment

2023-07-27 11:05 UTC, unai-reliefapp requested changes

2023-07-27 11:05 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/grid/grid.component.ts
>        await this.promisedAttachToRecord(
Instead of so many params, maybe we can switch that to something like this

```
await this.promisedAttachToRecord(
this.grid.selectedRows,
options
);
```
As all data comes from `options` object, and we are sending the whole `options`  as other param in this change, it's redundant and less clear

And then extract those in the `promisedAttachToRecord` as this:
```
const {targetForm, targetFormField, targetFormQuery, modifySelectedRows, modifications } = options;
```

2023-08-17 06:43 UTC, AntoineRelief commented
to be edited, so the steps are executed in this order:
- selectAll
- selectPage
- autoSave
- attachToRecord
- prefillForm
- modifySelectedRows
- notify
- publish
- sendMail
- goToNextStep | closeWorkflow

2023-08-21 12:43 UTC, AntoineRelief commented
@RenzoPrats 
in addition to what I put above:
attachToRecord -> should cancel the action if user clicks on cancel
prefillForm -> should cancel the action if user clicks on cancel

+ in the UI, when editing the action, please reorder the options, so they are ordered as described
+ in the UI, when editing the action, add a text above, telling that the steps will be executed in the displayed order

2023-08-25 08:39 UTC, AntoineRelief commented on libs/safe/src/lib/components/widgets/grid/grid.component.ts
> +  private blockModifySelectedRows = false;
@RenzoPrats 
it's not a correct approach
the code does not look well with this new parameter
I'll push new changes so you can compare

2023-08-25 09:22 UTC, merged