Ability to filter users question by role
ReliefApplications/ems-frontend pull request #1704
Opened 2023-08-08 02:15 UTC by matheus-relief

# Description

This PR adds the possibility to filter users question by role from the specified application

## Useful links
[Be able to filter user question by role](https://oortcloud.atlassian.net/jira/software/projects/OORT/boards/3?selectedIssue=OORT-658)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

See bellow

## Screenshots
![Peek 2023-07-12 11-40](https://github.com/ReliefApplications/oort-frontend/assets/102038450/73ae4ecd-236e-4596-a75c-9f7fb3169c27)

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-08 07:28 UTC, unai-reliefapp commented on libs/safe/src/lib/survey/components/users.ts
> +              choicesCallback(['', ...roles]);
```suggestion
              choicesCallback([{value: null, text: ''}, ...roles]);
```
We make sure all items follow same structure to avoid any unwanted behavior in all cases

2023-08-08 07:37 UTC, unai-reliefapp commented on libs/safe/src/lib/survey/components/users.ts
> +                !users.find((el) => el.value === user.id)
In order to make this checks more performant, I'll avoid to use the `.find` check as it's going to be heavier as users arrays goes up in length. Instead of checking each time if the user is already added, maybe would be better to once the users array is finished, get all unique values at once using lodash for example:

`users= uniqWith(users, isEqual)` https://lodash.com/docs/4.17.15#uniqWith

Most of the time the duplicate cases would be minimal and we avoid a whole find and additional check for each user iteration from the data

2023-08-08 07:39 UTC, unai-reliefapp requested changes
Changes to be checked

2023-08-09 01:49 UTC, matheus-relief commented on libs/safe/src/lib/survey/components/users.ts
> +                !users.find((el) => el.value === user.id)
Makes a lot of sense, thanks for the tip!

2023-08-09 06:00 UTC, unai-reliefapp approved these changes

2023-08-22 02:25 UTC, merged