Bugfix/ab#69091 db layers edition still broken
ReliefApplications/ems-frontend pull request #1706
Opened 2023-08-08 09:33 UTC by unai-reliefapp

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69091)
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-09 03:39 UTC, matheus-relief requested changes

2023-08-09 03:39 UTC, matheus-relief commented on libs/safe/src/lib/components/ui/map/layer.ts
> +    this.listeners = [];
I don't get what this does.

From what I understand, `this.listeners` is an array that will only ever contain `popupListeners`, why are we calling those functions (that pretty much just calls `this.popupService.setPopUp`) when removing all listeners?

2023-08-09 03:39 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +          ([[prev, next], trigger]) =>
```suggestion
          ([[, next]]) =>
```

2023-08-09 03:39 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +        next: ([[prev, next], trigger]) => {
```suggestion
        next: ([[prev, next]]) => {
```

2023-08-09 03:39 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
```suggestion
    if (!this.data.mapComponent || !this.isDatasourceValid) {
```

The issue where the legend is duplicated when you remove and add the geofiled again is still present, checking if the datasource is valid before setting up the layers seems to solve it.

![Peek 2023-07-12 11-40](https://github.com/ReliefApplications/oort-frontend/assets/102038450/c87cca1d-9dfc-4f7a-9f8b-5b0cd4014e61)

2023-08-09 03:52 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
I did some more testing and that does not fix the issue :disappointed:

2023-08-09 04:45 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
Seems like adding the following line to the beginning of `onRemoveLayer` fixes this issue. However, I'm not entirely sure it won't break something else

```ts
this.visibility = false;
```

2023-08-09 06:12 UTC, unai-reliefapp commented on libs/safe/src/lib/components/ui/map/layer.ts
> +    this.listeners = [];
Hi @matheus-relief , absolutely right, I thought I used renderer for creating the listener, that's why that syntax(e.g. https://gist.github.com/Shijir/5e6b291747c39c7243bf4a3430b393db#file-renderer2-mousemove-document-ts-L19)

I'll update it right now, thanks

2023-08-09 07:50 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +          ([[prev, next], trigger]) =>
I get  your point, but even if they are not used would not be better to keep those so other devs know what's the context for each position?(maybe we have to work with prev or trigger in the future and we will know what and where the are)

2023-08-09 08:01 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
mmm, you are right, if we zoom while the map is fetching the data from the server the onZoom triggers and as at that moment the map does not contain the layer, it adds it again:
```
if ( this.visibility &&
     !(layer as any).deleted &&

     *!map.hasLayer(layer)* 
) {
          map.addLayer(layer);
        }
```

I think that best solution would be to avoid any events while layer redraw from request is done, i'll double check that, thanks for spotting it!

2023-08-09 22:13 UTC, matheus-relief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +          ([[prev, next], trigger]) =>
Makes sense!

2023-08-09 22:18 UTC, matheus-relief approved these changes
lgtm!

2023-08-14 07:38 UTC, AntoineRelief commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
@unai-reliefapp 
cc @matheus-relief 
I think I still got an issue when editing layers..
you can see it while running the code with distant server, on app : 69091
I created a map with a group layer
the layers still got duplicated when zooming in / out

2023-08-14 14:50 UTC, taylordardono commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
@AntoineRelief Fix pushed in the last commit. 
Just one little thing, on updating the layer the backed returns the previous layer properties as seen in this image.
Data sent:
![image](https://github.com/ReliefApplications/oort-frontend/assets/79921564/04c8124c-1c2d-4a85-8de1-9bbd39720fae)
Data returned:
![image](https://github.com/ReliefApplications/oort-frontend/assets/79921564/0e632aab-37c2-4f41-8e00-5a762a3cda05)

For now, on successful request Im just adding the properties sent to the backend in the map layers list item to reflect the change in the layer list, but I guess that the edit layer endpoint should return the layer with the latest properties. I can take a look at that in the backend and open the PR. In the meantime the fix added in this PR would handle any name update for the layers in the map layers list.

KR, Unai

2023-08-14 14:53 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/map-settings/edit-layer-modal/edit-layer-modal.component.ts
> +    if (!this.data.mapComponent) {
@AntoineRelief Fix pushed in the last commit. 
Just one little thing, on updating the layer the backed returns the previous layer properties as seen in this image.
Data sent:
![image](https://github.com/ReliefApplications/oort-frontend/assets/79921564/04c8124c-1c2d-4a85-8de1-9bbd39720fae)
Data returned:
![image](https://github.com/ReliefApplications/oort-frontend/assets/79921564/0e632aab-37c2-4f41-8e00-5a762a3cda05)

For now, on successful request Im just adding the properties sent to the backend in the map layers list item to reflect the change in the layer list, but I guess that the edit layer endpoint should return the layer with the latest properties. I can take a look at that in the backend and open the PR. In the meantime the fix added in this PR would handle any name update for the layers in the map layers list.

KR, Unai

2023-08-16 13:11 UTC, AntoineRelief approved these changes

2023-08-16 13:11 UTC, merged