Fix 2.1.x/db#69081 group layer visibility range not working
ReliefApplications/ems-frontend pull request #1715
Opened 2023-08-09 11:15 UTC by NathanHGit

# Description

Added a parent layer variable to the layer component which contains the properties of the layer group. When zooming, it will check its maximum and minimum values to set the visibility of the layer.

## Useful links

Ticket: [69081 - DB - Group Layer visibility range not working](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69081)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I tried the zoom function on a personalized map composed of:
- 1 group layer, min zoom: 5, max zoom: 10
- layer 1, belongs to the group layer, min zoom 7, max zoom 9
- layer 2, belongs to the group layer, min zoom 2, max zoom 18

## Screenshots

![peek](https://github.com/ReliefApplications/oort-frontend/assets/65243509/6c7e97b6-9651-4188-96cd-7e56b53b5470)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-10 06:16 UTC, unai-reliefapp commented on libs/safe/src/lib/components/ui/map/layer.ts
> +      maxZoom = this.layerDefinition?.maxZoom || map.getMaxZoom();
Hi @NathanHGit , this two lines are repeated

```
maxZoom = this.layerDefinition?.maxZoom || map.getMaxZoom();
minZoom = this.layerDefinition?.minZoom || map.getMinZoom();
```

Do you see how can you keep just one definition of those?

pseudo code hint:

```
get zoom values from layerDefinition

if there is parentLayer
   get zoom values from parentLayer
   if zoom values are greater/lesser than the values from layerDefinition
     then take those values from parentLayer
```

2023-08-10 06:19 UTC, unai-reliefapp commented on libs/safe/src/lib/components/ui/map/layer.ts
> +  public parentLayer!: any;
I cannot see this property assigned anywhere in the code, please double check this

2023-08-10 06:19 UTC, unai-reliefapp requested changes
Maybe it's not finished as it's still a Draft PR, but if so please double check both comments
KR, Unai

2023-08-10 09:42 UTC, NathanHGit commented on libs/safe/src/lib/components/ui/map/layer.ts
> +  public parentLayer!: any;
This property is assigned at line 511 `child.parentLayer = this.layerDefinition;`

2023-08-11 06:23 UTC, unai-reliefapp approved these changes

2024-06-06 13:23 UTC, closed without merging

2024-06-06 13:23 UTC, AntoineRelief commented
closing this PR but I'll put the code in 2.x.x

it is mostly working