Feat 2.1.x/db#65456 sorting fields widget option improvements
ReliefApplications/ems-frontend pull request #1750
Opened 2023-08-22 13:35 UTC by NathanHGit

# Description

I removed the sortable boolean from the application settings object and I made sure that the sort resets when changing display mode. 

I also fixed some bugs:
- an error was created when event was null on onSort function
- the sort was not taken into account when searching for something
- the pagination was incorrect when you were in a different page than the first and searching for something (pagination was not reset)

## Ticket

https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/65456

## Type of change

- [X] New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

- I created a summary cards widget
- I selected the "Allow sorting" button in the widget display panel from widget options
- I added at least one field corresponding to the current layout in the list of the sorting panel
- I sorted my widget
- I changed display mode to "grid", and came back to "cards"
- I checked if sort select had been reset and the cards were in the correct order

## Sreenshots

![peek](https://github.com/ReliefApplications/oort-frontend/assets/65243509/277d0984-85a6-4677-89c2-5f2973e4b4bd)

# Checklist:

( * == Mandatory ) 

- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-08-22 15:14 UTC, unai-reliefapp commented
Hi @NathanHGit Please format the code correctly and push it again in order to see real changes and be able to review it correctly
Thanks

2023-08-22 20:04 UTC, RenzoPrats approved these changes
Working fine as expected, looks good to me!

2023-08-23 06:51 UTC, unai-reliefapp requested changes

2023-08-23 06:51 UTC, unai-reliefapp commented on libs/safe/src/lib/components/widgets/summary-card/summary-card.component.html
>      <div uiFormFieldDirective class="!m-0 w-44">
```suggestion
    <div uiFormFieldDirective class="items-center flex w-44">
```

From this:
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/33b7f10e-cb3a-4ea9-a1f3-b06c88eef44f)

To this:
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/0bf1a293-b0b6-4019-b716-73043ae32907)

2023-08-23 06:58 UTC, unai-reliefapp commented
Looks good to me, also the use of the skip property from the event instead of calculated from the paginator component is a fine improvement 👍

2023-09-11 10:55 UTC, merged