feat/AB#74292_ABC-Create-people-picker-question
ReliefApplications/ems-frontend pull request #1792
Opened 2023-09-04 14:26 UTC by TaiKamilla

# Description

this create a dropdown with multiple selections, that allows to search from users

## Useful links

- [link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/74292)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (refactor or addition to existing functionality)

## Screenshots

<img width="1129" alt="image" src="https://github.com/ReliefApplications/oort-frontend/assets/15035750/6950ea55-41e7-44e9-83d4-42a0cff07ba2">

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-06 10:45 UTC, NathanHGit reviewed
Maybe the username should be displayed instead of the id and I guess the select should be usuable from grid line editor as the owner field.

![image](https://github.com/ReliefApplications/oort-frontend/assets/65243509/235f01a0-b727-4ec6-bc23-b862b2fc8f25)

2023-09-27 08:00 UTC, MwanPygmay approved these changes
- As suggested by Nathan in above comment, added support in grids, and in summary cards: mimicked behavior of users questions.
- Repaired a bug regarding tagbox widget linked to one of my previous tickets (people tagbox would raise an error).
People question should work fine now.

2024-04-17 12:35 UTC, MwanPygmay commented
@Matthis-M-ReliefApps

-     Changed number of char for search to be 2
-     This feels unconsistant to me:

    in front :
    
![image](https://github.com/ReliefApplications/ems-frontend/assets/59645813/64a5979f-2a31-4a4b-927a-2911fc815601)

    in back:
    
![image](https://github.com/ReliefApplications/ems-frontend/assets/59645813/1128b826-cadb-4c44-8dcf-7605178e3089)

    shouldn't we just pass an empty filter when there is no filter from front?

2024-04-25 10:36 UTC, AntoineRelief commented on libs/shared/src/lib/survey/components/people.ts
> +      instance.applications = question.applications;
@Matthis-M-ReliefApps 
I think this is useless and copied from another question

2024-04-25 11:15 UTC, AntoineRelief commented
request to do for pagination:

query {
  users(limitItems: 25) {
      userid
      firstname
      lastname
      emailaddress
  }
  totalCount:users {
    aggregate_regionid_min
    aggregate_count
  }
}

2024-04-25 12:27 UTC, AntoineRelief commented
@MwanPygmay 

putting as draft this one

A few things to change:
- it should be possible to use it as multi select or single select ( perhaps an input could do it )
- in that case, when displaying in a grid, it should also be reflected ( I don't know if using the same type of question would allow it )
- too many users are fetched at the same time!! We should use pagination. One thing we can do, front-end side, is NOT to use our API, but instead, build a query to CS directly from the front-end. Or, in a first time, edit our back-end so we can do pagination over users list
- check if in export we have the same format than when displaying as a grid
- check if other widgets support the question type

I'll assign you the ticket on devops

2024-05-06 09:28 UTC, MwanPygmay commented
- New type of question: singlepeople, which is a single select
-   Behaviour adapted in grid, can be filtered
-   Fetching users ten by ten, with load on scroll.
-  corrected export.
-  Supported in summary cards and editor

2024-05-16 15:29 UTC, Matthis-M-ReliefApps requested changes
A few things to double-check but look overall fine

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/ui/core-grid/grid/grid.component.html
> +        [editable]="!field.disabled && field.meta.type !== 'people'"
Could it be cleaner if we disable all people-type fields by default instead of excluding it this way by hardcoding?

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +    '../../../../../../ui/src/lib/graphql-select/graphql-select.component.scss',
Could there be a cleaner way to do that?

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +        50 &&
Magic number

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +    if (searchValue.length >= 2 && searchValue !== this.previousSearchValue) {
Move magic number to CONST

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +        .filter((word) => word.length >= 3);
Why 3? Move magic number to CONST and add comment

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +        for (let index = 0; index < 2; index++) {
Feel like this could be better managed

2024-05-16 15:29 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/utils/parser/utils.ts
> +              value ? get(fieldsValue, field.name).length : 0
Double-check this please, I had an issue on loading resources type question but not sure it was related

2024-05-17 10:05 UTC, MwanPygmay commented on libs/shared/src/lib/utils/parser/utils.ts
> +              value ? get(fieldsValue, field.name).length : 0
![image](https://github.com/ReliefApplications/ems-frontend/assets/59645813/24f71c48-9609-42bf-8447-816a36d59a3a)
nope works from my side

2024-05-17 10:37 UTC, MwanPygmay commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +    '../../../../../../ui/src/lib/graphql-select/graphql-select.component.scss',
looks like meh https://github.com/angular/angular-cli/issues/9766

2024-05-17 11:47 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/survey/components/people-select/people-select.component.ts
> +        50 &&
yeah this one is ok

2024-05-17 11:54 UTC, Matthis-M-ReliefApps approved these changes
Another great PR from the GOAT Matthieu

2024-06-14 07:36 UTC, AntoineRelief commented
@Matthis-M-ReliefApps @MwanPygmay 

most of it is working as expected, but I still see one issue 😅

the charts are not working:

<img width="1150" alt="Capture d’écran 2024-06-14 à 09 22 26" src="https://github.com/ReliefApplications/ems-frontend/assets/50317271/28cfeeb2-a8fd-45a6-9c72-9dc4b40b2b1a">

We should see similar data than the one we see in other widgets
I'm putting back as draft the PR, and putting back in todo the ticket

2024-06-28 07:57 UTC, MwanPygmay commented
Still to be done:
- Sorting in the aggregations (sorting in the layouts is already handled).
- Bug: When filling out a form with the people picker and navigating directly to a grid displaying the people, the names do not appear immediately. The page needs to be reloaded to display the names.

2026-06-20 10:47 UTC, closed without merging