feat/AB#74580_add_pagination_main_users_in_backoffice
ReliefApplications/ems-frontend pull request #1822
Opened 2023-09-11 21:46 UTC by RenzoPrats

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-13 08:06 UTC, unai-reliefapp requested changes

2023-09-13 08:06 UTC, unai-reliefapp commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +    this.usersQuery.valueChanges.subscribe((resUsers) => {
Hi @RenzoPrats , now that we are adding new query subscriptions, please add the unsubscribe teardown logic for those(SafeUnsubscribeComponent),

```suggestion
    this.usersQuery.valueChanges.pipe(takeUntil(this.destroy$).subscribe((resUsers) => {
```

Same for the query of roles.
Thanks

2023-09-13 11:45 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +    this.usersQuery.valueChanges.subscribe((resUsers) => {
Hi @unai-reliefapp, I fixed it!
Thanks

2023-09-18 20:44 UTC, estelafs requested changes
Table pagination isn't updated when adding or deleting users and the filter only considers the visible contents of the table instead of refetching using the filters params. "On page changes" event don't update the pagination number after deleting, only after adding user. Requested changes in the backend as well.

2023-09-22 17:44 UTC, RenzoPrats commented
@estelafs I fixed these issues, if you could please review it again!

2023-09-25 14:33 UTC, estelafs approved these changes

2023-10-05 10:28 UTC, unai-reliefapp commented
@AntoineRelief Now that we add pagination feature to the user list, filter should be applied in the query now right? Not filtering current users in the front but an argument sent into the new paginated query

KR,  Unai

2023-10-27 14:48 UTC, Matthis-M-ReliefApps requested changes
Feels good to finally have pagination on this users list :+1: Especially with the new app that makes it grow to 5k users!
I took my time to review with a large scope so I have a bunch of questions

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
> +                });
What's the purpose of that?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
>        query: GET_PULL_JOBS,
Why the changes on pulljobs? Is that linked to another ticket?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on libs/safe/src/lib/components/users/users.component.ts
>          ? event.target.value.trim().toLowerCase()
Noticed that this is causing caps to go lowercase on the UI also, could you try to fix it also?
![Peek 27-10-2023 11-45](https://github.com/ReliefApplications/ems-frontend/assets/80319175/01da10f0-5558-40e9-ab36-9df346fe5e3b)

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +        });
Is there a reason to do this instead of `this.cachedUsers = this.cachedUsers.concat(e.data)` ?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
>                this.resources = this.resources.filter(
Why those changes here also?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.html
> -<safe-users [loading]="loading" [users]="users" [roles]="roles"></safe-users>
I think safe-users is used only on this page, is there a reason not to implement the paginator directly inside the <safe-users> component? I feel like it could've been easier no?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +    });
It's the first time "this.apollo.client.cache.evict" is used in the code, can you explain what's its purpose?

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  }
This seems to work correctly, but appears a bit too complicated to me. Would it be possible to restructure the code so the filters can be used as they are in _apps/back-office/src/app/dashboard/pages/applications/applications.component.html_
The filter is built and updated in app-filter:
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/e8b960da-c8a5-4c3d-aec4-fb5a49997793)
Then emitted as an event:
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/1de83a87-ec8d-4554-9997-7e6c4e4da574)
And directly used by the applications component like this:
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/373d67a5-2881-4bd7-9c30-54d1f5a790f7)
Which makes the whole flow way simpler. Could you check if that's possible in our case too? But if it's actually not possible or makes it more complicated, don't bother.

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  onPage(e: UIPageChangeEvent): void {
The logic seems right! However, could you explain why implement all this this way instead of using the same logic as in other components? (libs/safe/src/lib/components/notifications/notifications.component.ts, apps/back-office/src/app/dashboard/pages/resources/resources.component.ts, libs/safe/src/lib/views/application-users/components/user-list/user-list.component.ts, ...)

2023-10-27 14:48 UTC, Matthis-M-ReliefApps commented on libs/safe/src/lib/components/users/components/add-user/add-user.component.ts
> -import { Component, Inject, OnInit } from '@angular/core';
To explain the change on this file:
This is used when adding new users to the platform or application
I think there shouldn't be autocompletion here for two reasons:
1. When you're inviting from inside an application, even if you have rights to manage users inside the application, you're not supposed to see users outside of it, so you shouldn't have access to their emails, even as autocomplete
2. When you're inviting from outside an application, the users you want to add are, by definition, not in the system yet, so an autocomplete will never be possible.
Hence, I don't see a use case where the autocomplete is useful here, but please correct me if I'm wrong!

2023-10-27 17:22 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
> +                });
Hi @Matthis-M-ReliefApps the purpose of that is clear the cache, because when we add/remove some user and then we click in an item and then come back to the pagination we enter in something like this 
```
 if (cachedValues) {
      this.updateValues(cachedValues, false);
```
and we does not see the right pagination(not added the new user or not removed the user)

2023-10-27 17:24 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/pull-jobs/pull-jobs.component.ts
>        query: GET_PULL_JOBS,
It's because the pagination of the users was did based on the pagination of the pulljobs and I noticed an issue there, so I fixed it in the users and then in pulljobs

2023-10-27 17:27 UTC, RenzoPrats commented on libs/safe/src/lib/components/users/users.component.ts
>          ? event.target.value.trim().toLowerCase()
Yes, sure!

2023-10-27 17:51 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +        });
No reason, we can change to this.cachedUsers = this.cachedUsers.concat(e.data)

2023-10-27 18:20 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  onPage(e: UIPageChangeEvent): void {
Do you mean using handleTablePageEvent? I think we changed

2023-10-27 18:21 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.html
> -<safe-users [loading]="loading" [users]="users" [roles]="roles"></safe-users>
In fact, safe-users is used only on this page, so there's no specific reason for implement like this.

2023-10-27 18:25 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/resources/resources.component.ts
>                this.resources = this.resources.filter(
For delete the user when is clicked to delete an user.

2023-10-27 19:49 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  }
Yes, it's possible but we need first to change the pagination to safe-users.

2023-10-31 15:37 UTC, Matthis-M-ReliefApps commented on libs/safe/src/lib/components/users/users.component.ts
> +                  });
It works but I think you can try to improve it using lodash:
https://lodash.com/docs/4.17.15#intersection
Like get the intersection and check if there is at least one element in it, let me know if I'm not clear!

2023-10-31 15:37 UTC, Matthis-M-ReliefApps commented on libs/safe/src/lib/components/users/users.component.ts
> +                  }
Since all the snackbars are the same, I think you can just change the message and error? Like:

```
let messagePath = '';
let isError = false;
if (cond1) {
messagePath = "mess1"
} else if (cond2 {
messagePath = "mess2";
isError = true;
} else ...
}
this.snackBar.openSnackBar(this.translate.instant(messagePath), error: error);
```

It should clear a few lines! (Sorry I'm being super picky :laughing:)

2023-10-31 15:43 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/forms/forms.component.ts
> +                });
Thanks for the explanation Renzo! I don't have the expertise on Apollo so I will ask for another pair of eyes :laughing: 

Hi @unai-reliefapp ! Antoine advised me to check with you:
Since this is an Apollo functionality is present nowhere else in the code and we would add it, would you have a minute to dig on this and share your opinion? I'm a bit wary of any unexpected change in Apollo behaviour...
Thanks!!

2023-10-31 15:47 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.html
> -<safe-users [loading]="loading" [users]="users" [roles]="roles"></safe-users>
The new implementation looks good! Thanks!

2023-10-31 15:55 UTC, Matthis-M-ReliefApps commented
I noticed another issue while switching pages after changing the amount of users fetched, sometimes with 50 users set, the table only displays 10. Here's a GIF to demonstrate it:

![Peek 31-10-2023 16-52](https://github.com/ReliefApplications/ems-frontend/assets/80319175/293b7379-7b1a-4a4f-a8af-bb475ed06f69)

2023-10-31 16:00 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  onPage(e: UIPageChangeEvent): void {
Would something like this work in our case also?
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/ede5b1f6-8006-4225-9469-b3c248d902e5)

Seems quite simpler, but maybe I'm missing something?

Also, if you compare the length of cachedData and received data, what happens if we remove then add a user? Is the cache still updated or not?

2023-10-31 16:12 UTC, Matthis-M-ReliefApps requested changes
Some questions/changes still but it's looking better already! :+1:

2023-10-31 16:12 UTC, Matthis-M-ReliefApps commented on libs/safe/src/lib/components/utils/update-queries.ts
I think it's a good idea to regroup this in "libs/safe/src/lib" :+1: 

There seems to be 4 mostly identical files in the end :laughing: 
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/4981cc6d-5349-492f-bbc6-337787d4f35f)
Can you also remove the other duplicates in "back-office" so that's the only version? (to avoid duplication)

If that causes an import/build issue or anything else, please let me know.

Also, I recommend doing a merge from 2.x.x before this change to minimize the risks of conflicts.

2023-11-15 20:04 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/users/users.component.ts
> +  onPage(e: UIPageChangeEvent): void {
Done, indeed looks better!

2023-11-15 20:04 UTC, RenzoPrats commented on libs/safe/src/lib/components/users/users.component.ts
> +                  });
Improved using lodash!

2023-11-15 20:05 UTC, RenzoPrats commented on libs/safe/src/lib/components/users/users.component.ts
> +                  }
Done! Don't worry, I agree with these changes in fact looks better!

2023-11-15 20:06 UTC, RenzoPrats commented on libs/safe/src/lib/components/utils/update-queries.ts
Removed duplicated update-queries, it's working fine.

2023-11-15 20:07 UTC, RenzoPrats commented
> I noticed another issue while switching pages after changing the amount of users fetched, sometimes with 50 users set, the table only displays 10. Here's a GIF to demonstrate it:
> 
> ![Peek 31-10-2023 16-52](https://user-images.githubusercontent.com/80319175/279437585-293b7379-7b1a-4a4f-a8af-bb475ed06f69.gif) [ ![Peek 31-10-2023 16-52](https://user-images.githubusercontent.com/80319175/279437585-293b7379-7b1a-4a4f-a8af-bb475ed06f69.gif) ](https://user-images.githubusercontent.com/80319175/279437585-293b7379-7b1a-4a4f-a8af-bb475ed06f69.gif) [ ](https://user-images.githubusercontent.com/80319175/279437585-293b7379-7b1a-4a4f-a8af-bb475ed06f69.gif)

I was not able to reproduce this issue, I think it's working fine after I changed the onPage function as proposed in these comments.

2023-11-15 20:14 UTC, RenzoPrats commented
@Matthis-M-ReliefApps  I only found one more issue, when we add new users we should not add if it's already been added and display a message. The problem is that in the frontend we have two lists users and cachedUsers, the cachedUsers will store all the users that we already loaded but if we want to add an user that we already have but we didn't load yet we will be allowed, and in the backend we have the possibility to update the existing ones so we cannot return an error if we already have this user, so the only solution in this desing is frontend but as we didn't load everything from the beginning we cannot do it in the frontend too.

2023-11-23 15:54 UTC, MwanPygmay reviewed
Tested, read code.
There was a problem: no sorting on data implied mongo natural order, which is not sorted and resulted in lacks of data (because ids in mongo can make [1,2,3,5,4,6], and thus we could store the 5 as a cursor, then missing the 4). Fixed it by adding a sorting on created at (maybe name would be more coherent?)
Otherwise, looks good to me

2023-11-24 11:20 UTC, Matthis-M-ReliefApps approved these changes
I have a feeling that there could be some improvements to make on the way we use apollo caching/pagination/filtering (specifically, make better use of apollo existing cache system instead of using ou own cachedUsers on the users.component), but aside from this it seems to be working well!

2023-12-09 14:49 UTC, AntoineRelief commented on libs/safe/src/index.ts
> +export * from './lib/utils/update-queries';
check line above, there was already a file meant to export code from utils folder

2023-12-09 16:31 UTC, AntoineRelief commented
closing and putting more of changes + some additional ones in this pr:
https://github.com/ReliefApplications/ems-frontend/pull/2147

2023-12-09 16:31 UTC, closed without merging