feat/AB#75137-use-button-for-close-in-all
ReliefApplications/ems-frontend pull request #1837
Opened 2023-09-15 16:40 UTC by estelafs

# Description
To keep the consistency I searched for modals and pages that used the close icon + "Cancel" button instead of a "Close" button, removed the close icon of the ui-dialog and updated the components that used it changing the "Cancel" buttons for "Close" buttons, since it does the same thing and a lot of components already used this

## Useful links
- Please insert link to ticket: https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/75137

## Type of change
- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?
Please see the screenshots below

## Screenshots

![3](https://github.com/ReliefApplications/oort-frontend/assets/28535394/8d2b47cc-c293-4e32-8ec2-e55f5fc85129)
![close](https://github.com/ReliefApplications/oort-frontend/assets/28535394/bd0a6807-2836-4385-a24f-8165beddfc28)
![preferences](https://github.com/ReliefApplications/oort-frontend/assets/28535394/588eb0e1-35dd-435d-a789-db2a688ab787)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-18 14:19 UTC, RenzoPrats approved these changes
It's working fine, looks good to me!

2023-09-18 14:58 UTC, unai-reliefapp commented
https://github.com/ReliefApplications/oort-frontend/blob/223d9f868cd05b539c8527e11a6e8fc80a361459/libs/safe/src/lib/components/email-preview/email-preview.component.html#L57-L59

This one should be changed with the Close text? @estelafs 

Also maybe we can use this ticket to set all the close buttons using the uiCloseDialog directive instead using a click function in order to keep the components overkill method free and same case for all buttons:

```
<ui-button (click)="onClose()">
      {{ 'common.close' | translate }}
 </ui-button>
```
to
```
<ui-button uiDialogClose>
      {{ 'common.close' | translate }}
 </ui-button>
```

And remove any related function in the component class .ts

What do you think?

2023-09-18 14:58 UTC, unai-reliefapp reviewed
Please take a look to my comment below the description

2023-09-18 18:00 UTC, estelafs commented
@unai-reliefapp good point! Well remembered, thanks

2023-09-19 06:26 UTC, unai-reliefapp requested changes

2023-09-19 06:26 UTC, unai-reliefapp commented on apps/back-office/src/app/components/add-form-modal/add-form-modal.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on apps/back-office/src/app/components/add-resource-modal/add-resource-modal.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on apps/back-office/src/app/dashboard/pages/api-configurations/components/add-api-configuration/add-api-configuration.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on apps/back-office/src/app/dashboard/pages/applications/components/chose-role/chose-role.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on apps/back-office/src/app/dashboard/pages/reference-datas/add-reference-data/add-reference-data.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/access/edit-access/edit-access.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/choose-record-modal/choose-record-modal.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.cancel' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.cancel' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/convert-modal/convert-modal.component.html
> +    <ui-button uiFormFieldDirective>{{ 'common.close' | translate }}</ui-button>
```suggestion
    <ui-button uiDialogClose>{{ 'common.close' | translate }}</ui-button>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/mapping/mapping-modal/mapping-modal.component.html
> +    <ui-button uiFormFieldDirective>
```suggestion
    <ui-button uiDialogClose>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/record-modal/record-modal.component.html
> +      <ui-button uiFormFieldDirective>
```suggestion
      <ui-button uiDialogClose>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/record-modal/record-modal.component.html
> +      <ui-button uiFormFieldDirective variant="danger">
```suggestion
      <ui-button uiDialogClose variant="danger">
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/roles/components/add-role/add-role.component.html
> +    <ui-button uiFormFieldDirective>
```suggestion
    <ui-button uiDialogClose>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/users/components/add-user/add-user.component.html
> +    <ui-button uiFormFieldDirective>
```suggestion
    <ui-button uiDialogClose>
```

2023-09-19 06:26 UTC, unai-reliefapp commented on libs/safe/src/lib/components/users/components/invite-users/invite-users.component.html
> +    <ui-button uiFormFieldDirective>
```suggestion
    <ui-button uiDialogClose>
```

2023-09-19 12:23 UTC, unai-reliefapp approved these changes

2023-10-06 14:31 UTC, MwanPygmay reviewed
-Merged 2.x.x
-Removed the 'closable' parameter of the ui dialog component
-Added a close button in the bottom for all dialog components (some were missing)
-Added a button in the top right part of the dialogs (the div around the ng-content is just there so that if the header is missing, for example in the expanded widgets (maybe a bug btw), the close button is still to the right)

2023-10-09 08:36 UTC, AntoineRelief commented
@MwanPygmay 
when you push new changes that affect the ui, please change the screenshots

2023-10-09 09:36 UTC, AntoineRelief commented on libs/ui/src/lib/dialog/dialog.component.html
> +  <div class="flex justify-between">
@MwanPygmay 
I don't like
for me it looks worse than before:
![Capture d’écran 2023-10-09 à 11 35 29](https://github.com/ReliefApplications/oort-frontend/assets/50317271/bfbb5c49-a2c7-46e4-9cca-b6245aced308)

2023-10-09 09:42 UTC, merged