Fix/ab#75167 prefill user data after saved one
ReliefApplications/ems-frontend pull request #1838
Opened 2023-09-15 20:04 UTC by RenzoPrats

# Description

Fixed prefill user data when using "new record" after having saved one.

## Useful links

[ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/75167)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

It has been tested creating a form with some fields with default value expressions as described in the ticket and adding a record and then clicking in "new record" and verifying if the fields were prefilled.

## Screenshots

![Peek 15-09-2023 17-02](https://github.com/ReliefApplications/oort-frontend/assets/56398308/3e0e425b-9a9e-436b-bfcb-e4b5ed223a65)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-18 15:01 UTC, unai-reliefapp requested changes

2023-09-18 15:01 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form/form.component.ts
> +      this.formHelpersService.addUserVariables(this.survey);
ey @RenzoPrats Could you please move this new feature into a single function inside the class to avoid code duplication?
Thanks

2023-09-18 17:33 UTC, RenzoPrats commented on libs/safe/src/lib/components/form/form.component.ts
> +      this.formHelpersService.addUserVariables(this.survey);
@unai-reliefapp sure, it's done.
Thanks.

2023-09-19 06:20 UTC, unai-reliefapp approved these changes

2023-09-19 15:20 UTC, AntoineRelief commented on libs/safe/src/lib/components/form/form.component.ts
> +          //verify if the defaultExpression is setted in variables
@RenzoPrats 
I'm seeing you're doing that whenever you comment
please leave a space between '//' and the text

2023-09-20 15:06 UTC, AntoineRelief commented on libs/safe/src/lib/components/form/form.component.ts
> +    surveyQuestion.forEach((question: any) => {
@RenzoPrats 
aware of the naming
there, this.survey.getAllQuestions return an array, but you're using singular for the const
make sure to prefer plural in that case

2023-09-20 15:08 UTC, AntoineRelief commented on libs/safe/src/lib/components/form/form.component.ts
> +   * Set user variables
@RenzoPrats 
the comment there is not enough
it's exactly the name of the method, so we already have this information from the method name
you should explain more the logic, tell what the method does

2023-09-20 15:22 UTC, merged