Now the form builder empties all customFilters if any other filterBy …
ReliefApplications/ems-frontend pull request #1875
Opened 2023-09-22 02:44 UTC by brunotannus

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- (https://oortcloud.atlassian.net/jira/software/projects/IM/boards/5?selectedIssue=IM-40)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- Create a form with a resource question and set a custom filter (json), then select a filter by question from the dropdown and save the form. When editing the form again and selecting the blank space from the filter by question to make the custom filter visible it should not display the previous json you added previously anymore.
- 
## Screenshots

![image](https://github.com/ReliefApplications/oort-frontend/assets/39497117/10f9974b-eb41-452c-97e7-d19434026e7b)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings

2023-09-25 09:45 UTC, unai-reliefapp commented on libs/safe/src/lib/components/form-builder/form-builder.component.ts
> +    this.surveyCreator.survey
ey @brunotannus this works indeed, but let's try to keep features related to the question type they are going to use, survey is a chaos by itself, let's try not to feed that 😅 

I'll recommend you to go to each question type that uses the `filterBy` and `customFilter` (resource.ts and resources.ts) property, and in the `onLoaded` function, set a listener to the `filterBy` property that would clean up the 
`customFilter` property field, e.g.

```
question.registerFunctionOnPropertyValueChanged('filterBy', () => {
      question.customFilter = null;
});
```

Thanks,
KR, Unai

2023-09-25 09:50 UTC, unai-reliefapp requested changes
Please check the comments

2023-09-25 14:31 UTC, unai-reliefapp approved these changes

2023-09-28 02:39 UTC, matheus-relief approved these changes

2023-09-28 02:47 UTC, merged