Feat/ab#75754 reduce white space backoffice when editing applications
ReliefApplications/ems-frontend pull request #1891
Opened 2023-09-25 19:08 UTC by RenzoPrats

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-26 07:42 UTC, MwanPygmay approved these changes
read code, watched changes, looks good to me.

2023-09-26 14:27 UTC, AntoineRelief commented
@RenzoPrats 
@MwanPygmay 

For future PRs,
also take into consideration how the UI is affected by the ticket
there, for example, the purpose of the ticket is to reduce the space used by the header, but as it was coded, the header is bigger than before..

<img width="1440" alt="Capture d’écran 2023-09-26 à 16 24 29" src="https://github.com/ReliefApplications/oort-frontend/assets/50317271/fa8907a1-162e-4331-8c99-15b267d22891">

2023-09-26 14:28 UTC, AntoineRelief commented on libs/shared/src/lib/components/layout/layout.component.ts
> +  @Input() settings: any[] = [];
@RenzoPrats 
cc @MwanPygmay 
comments !
whenever possible, add comments, even for class properties

2023-09-26 14:31 UTC, AntoineRelief commented
@RenzoPrats 
@MwanPygmay 

unwanted issue created by the code:
<img width="663" alt="Capture d’écran 2023-09-26 à 16 29 36" src="https://github.com/ReliefApplications/oort-frontend/assets/50317271/8a5d6dfc-5911-4d61-926e-b71439c27192">

as you can see above, the permissions icon of the page is now white, and so, not visible!

2023-09-26 14:32 UTC, AntoineRelief requested changes
@RenzoPrats 
@MwanPygmay 
Will put this one back into progress, it's not working fine

2023-09-26 20:03 UTC, RenzoPrats commented
@AntoineRelief @MwanPygmay I added coments in the new inputs, corrected the size of the header, and set back the grey color to the settings and permission buttons (but I guess white was more visible), the only persistent issue is about responsive, I'm not sure how it should work but for now the settings, permissions and publish button is being hidden as the page decreases size, if you @MwanPygmay can check please.

2023-09-27 08:38 UTC, MwanPygmay reviewed
- Comments were added
- Header size was corrected
- Permissions icon is not white anymore, although I am not sure about what you mean by 'as you can see above, the permissions icon of the page is now white, and so, not visible!' @AntoineRelief, to me grey is less visible but it presents the advantage of contrasting with the title

2023-09-28 12:57 UTC, AntoineRelief commented on libs/shared/src/lib/components/layout/layout.component.ts
> +  @Input() settings: any[] = [];
@RenzoPrats 
jsdoc comments ;)
so starting with /**
and ending with */

2023-09-29 08:21 UTC, merged

2023-09-29 08:24 UTC, AntoineRelief commented
@RenzoPrats 
cc @MwanPygmay 

You overcomplexified the ticket 
Indeed, the layout already had a property to inject a header template, so by putting the component inside the layout in order to display when no header was provided, you created a logic that could have been avoided

I changed that, by putting the application-toolbar component in the back-office, renaming it to application-header, changing the logic to be simplified, and then, injecting it as the header in the layout, so the layout does not need to import the component

Please keep that in mind for future tickets
Template injection is quite a powerful feature of Angular, that can simplify the code