added column in grid to go to record specific dashboard
ReliefApplications/ems-frontend pull request #1897
Opened 2023-09-27 20:14 UTC by RenzoPrats

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-09-29 18:55 UTC, estelafs approved these changes
- Update some comments to keep consistency and added a tooltip to the record id checkbox to inform that is used to redirect the user to the context view of the record.

- Fixed page url generation because it wasn't working in the front-office (the 'applications' url params were always added, since the url need used was saved always in the back-office)

Taking this into consideration, everything is working as expected.

2023-10-05 07:17 UTC, unai-reliefapp commented on libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
> +      setTimeout(() => {
Hi @RenzoPrats , every time we use a timeout or interval we should now store the result and clean it up as a regular observable in order to avoid memory leaks

Declare a new property like
`private pageChangeTimeoutListener!: NodeJs.Timeout`
```
// Add this before any assignation to timeout listeners to clear any previously stored value
// And also add this check in the components ngOnDestroy hook to clean it up definitely on component destruction
if(this.pageChangeTimeoutListener){
  clearTimeout(this.pageChangeTimeoutListener);
}
this.pageChangeTimeoutListener = setTimeout(() => {
```

2023-10-05 07:20 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.ts
> +      ?.valueChanges.subscribe((val: boolean) => {
```suggestion
      ?.valueChanges.pipe(takeUntil(this.destroy$).subscribe((val: boolean) => {
```

2023-10-05 08:28 UTC, unai-reliefapp commented
@AntoineRelief Would not be better to have the checkbox to set the record id inline with the menu select instead of in block and with so much space in between?
Currently
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/846700e1-9bde-4f74-b759-0d2ee7ae1284)

Proposal:
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/23e0d1a8-be4c-4abe-a7f9-dc5e5535a8b7)

Or at least without that many space in between select and checkbox:
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/c52c8328-d97d-40f5-bd8e-0fe9d797bbc7)

Also just to confirm, the pages available should be the ones in the same application of the current widget settings that we are editing?

KR, Unai

2023-10-05 08:29 UTC, unai-reliefapp requested changes
Is there a reason why for the actions in the layout and aggregations settings are seen this way in this branch 😕 
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/b067f4b3-1ca4-48b2-a06c-9f4423619ccb)

2023-10-05 08:31 UTC, AntoineRelief commented
@unai-reliefapp 
what I'd suggest is to keep that in two lines, but to have some space on the left or any indicator that would indicate that these two options are linked to the toggle "show record dashboard view"
Btw, I've already said that this name: "show record dashboard view" is not correct, and I'd prefer something like:
"navigate to page"

2023-10-05 08:31 UTC, AntoineRelief commented
> Is there a reason why for the actions in the layout and aggregations settings are seen this way in this branch 😕 ![image](https://user-images.githubusercontent.com/123092672/272833490-b067f4b3-1ca4-48b2-a06c-9f4423619ccb.png)

this is fixed in beta @unai-reliefapp

2023-10-05 08:49 UTC, unai-reliefapp commented
> @unai-reliefapp what I'd suggest is to keep that in two lines, but to have some space on the left or any indicator that would indicate that these two options are linked to the toggle "show record dashboard view" Btw, I've already said that this name: "show record dashboard view" is not correct, and I'd prefer something like: "navigate to page"

Something like this?
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/48091cac-050a-4f13-83fa-0565358fecd5)

Also please @RenzoPrats update the translation with the "Navigate to page" label plus also add the missing values for the french language

2023-10-05 14:05 UTC, RenzoPrats commented
> > @unai-reliefapp what I'd suggest is to keep that in two lines, but to have some space on the left or any indicator that would indicate that these two options are linked to the toggle "show record dashboard view" Btw, I've already said that this name: "show record dashboard view" is not correct, and I'd prefer something like: "navigate to page"
> 
> Something like this? ![image](https://user-images.githubusercontent.com/123092672/272840396-48091cac-050a-4f13-83fa-0565358fecd5.png)
> 
> Also please @RenzoPrats update the translation with the "Navigate to page" label plus also add the missing values for the french language

Hi @unai-reliefapp , the repairs were made, please check it again, thanks!

2023-10-06 10:22 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
> +      showRecordDashboard: [
@RenzoPrats 
cc @unai-reliefapp 
When I asked to change the text, I also meant to change that
I'll do it, but the name of the settings like that do not make sense based on new display

2023-10-06 10:23 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
> +    <div class="flex flex-col gap-2 mb-2">
@RenzoPrats 
cc @unai-reliefapp 
usually, you don't want the item which would always be displayed to set the margin
the margin should be set by the elements that appear based on conditions

2023-10-06 10:26 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
> +      pageIdUrl: [get(configuration, 'actions.pageIdUrl', '')],
@RenzoPrats cc @unai-reliefapp 
I don't like the name of this parameter
pageIdUrl, what is it? an id or an url?
I think it's an id, so just use id

2023-10-06 10:27 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
> +    <div class="flex flex-col gap-2 mb-2">
@RenzoPrats cc @unai-reliefapp 
looking at it again, I understand it may be because the overflow hides the animation of the toggle
in that case, you can put the margin or padding at parent level ( around all the toggles )

2023-10-06 10:28 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
> +            <ng-container ngProjectAs="label">
@RenzoPrats cc @unai-reliefapp 
not enough space between both

2023-10-06 10:29 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/grid-settings/tab-actions/tab-actions.component.html
> +    <div class="flex flex-col gap-2 mb-2">
true, plus I don't see any left padding according to the toggle label as I placed in the image
Please also add that @RenzoPrats , thanks

2023-10-06 10:29 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/summary-card-settings/summary-card-settings.component.ts
> +      showRecordDashboard: [
@RenzoPrats 
cc @unai-reliefapp 
perhaps we could have pageId and useRecordId as sub-parameters of this one, otherwise, all the properties are at the same level, which does not really make sense for pageId and useRecordId, as they would only appear if the navigation to page is enabled

2023-10-06 20:40 UTC, RenzoPrats commented on libs/shared/src/lib/components/widgets/grid-settings/grid-settings.forms.ts
> +      pageIdUrl: [get(configuration, 'actions.pageIdUrl', '')],
It's the url of the page, so I changed the name to pageUrl and also the text displayed to "Page source url".

2023-10-06 20:43 UTC, RenzoPrats commented
Changes requested were made, I also did some fix in the summary card when it's displayed as grid to it work correctly. Please review it again @AntoineRelief @unai-reliefapp and let me know if some issue stil.

2023-10-09 12:00 UTC, unai-reliefapp commented
Does this column title suit you @AntoineRelief ?
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/426bdeb2-64cd-4025-90fd-d20d9db8b2a9)

Also in the page dropdown we are also displaying form type and workflow type pages of the current application.
Should go display a least of pages of all applications, just the pages of the current application, and if so, only the dashboard types?
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/eded7afa-cc3b-4808-a683-2ad465cfbe32)

Besides that I think it's ready, i refactor the grid actions form group to a new function for both grids and summary cards, plus also I change the page change through location in order to happen once the data is ready, not using a timeout. Also fixed the spacing in order to be align to the rest of labels

KR, Unai

2023-10-13 11:11 UTC, AntoineRelief commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +          this.location.replaceState(this.location.path(), undefined, {
@RenzoPrats 
@unai-reliefapp 

could one of you explain me why we need that?

2023-10-13 11:15 UTC, unai-reliefapp commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +          this.location.replaceState(this.location.path(), undefined, {
the location thing?

2023-10-13 12:18 UTC, AntoineRelief commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +          this.location.replaceState(this.location.path(), undefined, {
yes, why do we have that ? I don't see any comment about this, and it's not used anywhere else in the code, so I don't get it

2023-10-13 12:23 UTC, unai-reliefapp commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +          this.location.replaceState(this.location.path(), undefined, {
WHO wanted to save the current pagination state of the table from where the record was open in order to load the same paginated list once the user goes back from the open record in the dashboard view.
The location would save the that state so when the user goes back from the record and loads the application again, the grid would trigger a pagination after the data is loaded using the previously saved location state, which would be cleaned up after it's used.
I left a quick explanation also in my last comment in the PR.
@RenzoPrats please add comments in this part of the code why and how the location is used for loading previous paginated list in the grid.

2023-10-13 14:27 UTC, AntoineRelief commented
moved the code to beta branch
I need someone to remove the feature discussed above about being able to save the location for pagination
it's too soon for this feature, as we would need additional things about filtering / sorting to be saved as well

2023-10-13 14:28 UTC, AntoineRelief commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +    private location: Location
to be removed

2023-10-13 14:28 UTC, AntoineRelief commented on libs/shared/src/lib/components/ui/core-grid/core-grid.component.ts
> +          this.location.replaceState(this.location.path(), undefined, {
to be removed

2023-10-13 14:28 UTC, AntoineRelief commented on libs/shared/src/lib/components/ui/core-grid/grid/grid.component.ts
> +    Location,
to be remvoed

2023-10-13 14:29 UTC, unai-reliefapp commented
Would you mind to remove those lines for the Location @RenzoPrats ?
Thank you

2023-10-13 18:55 UTC, RenzoPrats commented
> Would you mind to remove those lines for the Location @RenzoPrats ? Thank you

Hi @unai-reliefapp, No that's fine, I will remove it.

2023-10-16 09:19 UTC, merged

2023-10-16 09:41 UTC, AntoineRelief commented
@unai-reliefapp 
just fixed the issue with validators on main branch, thanks for pointing out the issue 👍