Feat/ab#69019 allow user with read permission duplicate applications and page
ReliefApplications/ems-frontend pull request #1930
Opened 2023-10-04 15:37 UTC by RenzoPrats

# Description

Allowed users with read permission duplicate pages and applications instead of only with update permissions

## Useful links

[ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/69019)
[backend](https://github.com/ReliefApplications/oort-backend/pull/763)

## Type of change

- [X] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

It has been tested verifying if users with read permission can now duplicate pages and applications.

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-05 07:06 UTC, unai-reliefapp requested changes
Hi @RenzoPrats , please double check and confirm that all duplicate actions in the page are updated accordingly
![image](https://github.com/ReliefApplications/oort-frontend/assets/123092672/5a5709e4-ba01-4d6e-939f-b2efdb049aaa)
KR, Unai

2023-10-05 12:16 UTC, RenzoPrats commented
> Hi @RenzoPrats , please double check and confirm that all duplicate actions in the page are updated accordingly ![image](https://user-images.githubusercontent.com/123092672/272810568-5a5709e4-ba01-4d6e-939f-b2efdb049aaa.png) KR, Unai

Hi @unai-reliefapp, I think the only duplicate action that was not updated was in the settings of the aplication because I'm not sure if an user without canUpdate permission can acess it, but now I updated it also. Thank you!

2023-10-16 11:04 UTC, AntoineRelief commented
merged newest version of beta in it
things I see missing:
- with the new way to display settings of applications, I don't believe we cover a case where you can read the application but not update it. In that case, we must check that:
  - only people with read / update access of the app can open settings of a page
  - if you just have read access to the app, you should only see some part of the settings ( or see them as deactivated, that's certainly better )
 
![Capture d’écran 2023-10-16 à 13 03 35](https://github.com/ReliefApplications/ems-frontend/assets/50317271/e2550224-7b55-4b68-abb2-67798bf23d3f)

![Capture d’écran 2023-10-16 à 13 03 24](https://github.com/ReliefApplications/ems-frontend/assets/50317271/d8079d97-491e-4c7b-bb7f-f6d5e981d52c)

so from screenshots above, only the "duplicate" action should be accessible to an user that can only read the app
you need to use: @casl/angular in order to do that

2023-10-17 09:51 UTC, AntoineRelief commented on apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.html
> +            [disabled]="!('read' | able : 'Application')"
@RenzoPrats 
it's not the logic to apply
there, the user can see the page, and, perhaps, can edit it
so in all cases, it will be able to see the settings
no need to test anything, and the test there is not correct

2023-10-17 09:53 UTC, AntoineRelief commented on apps/back-office/src/app/dashboard/pages/applications/applications.component.html
> +                *ngIf="element.canSee"
@RenzoPrats 
it's a bit confuse
one elements where you should have put the test on ability to create a new application, you put tests on the element itself, but on some others places, where the logic should have been thought on the element, you put a test about the global model 
i'll create a documentation about that, I see it's still confuse

2023-10-17 10:46 UTC, merged