No ticket yet : POC for hiding vertical menu by default
ReliefApplications/ems-frontend pull request #1953
Opened 2023-10-12 12:37 UTC by LenaelleRelief

# Description

Adds a selection in the app settings to show or not the vertical menu by default. Not available if vertical menu is not selected.

## Useful links

- Link to back-end coming soon 

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Tested with both new and old apps

## Screenshots

![image](https://github.com/ReliefApplications/oort-frontend/assets/103029022/322db091-768d-4b67-a217-3765603a6ae1)
![image](https://github.com/ReliefApplications/oort-frontend/assets/103029022/6b83fe06-2170-4be9-a949-bd360a11dae6)

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-12 19:34 UTC, RenzoPrats commented on apps/back-office/src/app/application/pages/settings/settings.component.html
> +      >=)
```suggestion
      >
```

2023-10-12 19:59 UTC, RenzoPrats requested changes
Hi @LenaelleRelief, I found this issue I think it's a bug 
![Peek 12-10-2023 16-33](https://github.com/ReliefApplications/oort-frontend/assets/56398308/3cd15c1e-6e89-4c4f-a50d-99a322697303)
When we edit some setting and save it, we are not able to modify and save again only if we reload the page.

2023-10-13 07:17 UTC, LenaelleRelief commented
Hi ! @RenzoPrats thanks a lot ! I indeed noticed this bug but since it was also impacting the "side menu" selector, I thought it was outside the scope of this PR, that's good if you did it anyway aha

Can you confirm that with this solution, it is possible to update the "side menu" selection again after already saving it ?

2023-10-13 12:15 UTC, AntoineRelief commented
> Hi ! @RenzoPrats thanks a lot ! I indeed noticed this bug but since it was also impacting the "side menu" selector, I thought it was outside the scope of this PR, that's good if you did it anyway aha
> 
> Can you confirm that with this solution, it is possible to update the "side menu" selection again after already saving it ?

it's out of scope of this PR
as it was not based on correct branch, the issue you described is solved in beta branch

2023-10-13 13:12 UTC, RenzoPrats approved these changes
Ah okay, I didn't know, so despite of that is working fine!

2023-11-07 16:48 UTC, closed without merging

2023-11-07 16:49 UTC, AntoineRelief commented
@LenaelleRelief 
closing this one
I'll push similar changes directly on beta
thanks!