Feat/ab#74320 navigation to and after data input form
ReliefApplications/ems-frontend pull request #2023
Opened 2023-10-30 14:37 UTC by unai-reliefapp

# Description

feat: add new custom record editor button in tinymce editor toolbar for widget content
feat: add event listener to html widget content in order to open related record edition modal;

## Useful links

- [Link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/74320)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please refer to screenshots below

## Screenshots

New edit record button
![editor button](https://github.com/ReliefApplications/ems-frontend/assets/123092672/aa5de50f-bb45-4e56-aea9-edbc112b354e)

Editor button display in content:
![editor display](https://github.com/ReliefApplications/ems-frontend/assets/123092672/887e3a63-7fc9-4603-a88c-5bbbbbdb7cca)

Position change:
![editor button change position](https://github.com/ReliefApplications/ems-frontend/assets/123092672/559925ec-d917-4c9f-9111-bacbe67fe83e)

Editor display in change position:
![editor display change position](https://github.com/ReliefApplications/ems-frontend/assets/123092672/ca091dfa-bd03-404b-a964-f272b64544eb)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-30 14:55 UTC, AntoineRelief commented
@unai-reliefapp 
should be good yes 👍

2023-10-31 09:29 UTC, unai-reliefapp commented
⚠️  **IMPORTANT** ⚠️ 

Ideal thing would be to check the display of the editor button in the toolbar within the tinymce config somehow, but i could not find a way yet. If someone finds it, please feel free to updat the PR

KR, Unai

2023-11-20 07:40 UTC, AntoineRelief commented
I think the PR is modifying too many files...
Perhaps there's an easier way to do that
I liked the approach we had for the html content component, but adding additional inputs / outputs in it makes it quite different

Another thing I'd like to try, could it be possible to consider the "edit" event like as a link? So you can put it anywhere, like on a div, a h1 etc, and when you click on the target element, then you open the modal

2023-11-22 12:35 UTC, AntoineRelief requested changes
see comments

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/common/html-widget-content/html-widget-content.component.ts
> +  @Input() dataSource!: { record: any; layout: any };
@unai-reliefapp please try to add jsdoc on top of properties

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +import { EDIT_RECORD } from './graphql/mutation';
this isn't working, as the file just doesn't exist

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +    const recordEditor = htmlWidgetContent.querySelector('#record-editor');
it should not work like that
if you have multiple buttons to do the edit, I doubt this can work if you click on the second one, as the query will fetch the first one
in that case, the target doesn't match

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +            this.apollo
does it refresh the card after saving?
it should

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
> +    private dataTemplateService: DataTemplateService,
the two elements there seems to be useless?

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
> +import { EDIT_RECORD } from '../graphql/mutation';
same comment there, the file just doesn't exist

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
> +    const recordEditor = cardContent.querySelector('#record-editor');
same comment than before

2023-11-22 12:35 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item/summary-card-item.component.ts
> +              .subscribe({
same comment than before, it should refresh when saved

2023-11-22 14:19 UTC, MwanPygmay commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +import { EDIT_RECORD } from './graphql/mutation';
added the files (copy pasted the request Unai previously wrote)

2023-11-22 14:20 UTC, MwanPygmay commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +    const recordEditor = htmlWidgetContent.querySelector('#record-editor');
Added class instead of id as there can be several of them. Now fetch all of them

2023-11-22 14:20 UTC, MwanPygmay commented on libs/shared/src/lib/components/widgets/editor/editor.component.ts
> +            this.apollo
added refresh for both text editor and summary card

2023-11-22 14:24 UTC, MwanPygmay commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
> +    private dataTemplateService: DataTemplateService,
used to detect the click event

2023-12-06 12:13 UTC, closed without merging

2023-12-06 12:14 UTC, AntoineRelief commented
reproduced changes in alpha branch directly
some parts of the PR were incorrect:
- incorrect usage of the record in the widgets ( we should still store the id, not the whole record )
- easier to use direct reference to parent in some cases