AB#74319 : Save records as draft
ReliefApplications/ems-frontend pull request #2030
Opened 2023-10-31 16:40 UTC by LenaelleRelief

# Description

Adds a new feature that allows the user to save draft records and select them to fill a form again.
User story 74319 
Ticket 77590
Not a 100% sure I added JSCode everywhere...Sorry

## Useful links

- Please insert link to ticket : 

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

- [x] Tested in back-office with different forms

## Screenshots

![image](https://github.com/ReliefApplications/ems-frontend/assets/103029022/1c441009-5faf-416a-b4ad-db4e6ac9b3fb)

![image](https://github.com/ReliefApplications/ems-frontend/assets/103029022/eb8b7a39-e8d5-4ba2-b9de-01f9fe1bb1fe)

![image](https://github.com/ReliefApplications/ems-frontend/assets/103029022/2e3d6418-6432-4aa7-9082-0ceceaa0a4be)

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-10-31 20:14 UTC, estelafs approved these changes
Everything working as expected, i just did some small improvements:
Added missing JSDocs and translations, removed console logs and unused imports, added data checks and added the empty template when table don't have drafts to display

Also, @AntoineRelief , the draft feature should be available in the here in the shared-form-modal when adding or updating a record from a grid?

![Screenshot from 2023-10-31 17-05-19](https://github.com/ReliefApplications/ems-frontend/assets/28535394/82236bca-18de-431e-aa1a-270c8fa39135)

2023-11-06 11:38 UTC, AntoineRelief commented on libs/shared/src/i18n/en.json
> +					"confirmDelete": "Do you really want to delete this draft record ?",
@LenaelleRelief @estelafs 
for your own knowledge, no space between the sentence and the "?" in english ( I don't like that, but that's how it is 😅 )

2023-11-06 11:44 UTC, AntoineRelief commented on libs/shared/src/lib/components/draft-record-modal/draft-record-modal.component.ts
> +   * Creates an instance of DraftRecordModalComponent.
@LenaelleRelief cc @estelafs 
the comment there is not good
constructor must have a similar jsdoc description to the component itself

2023-11-06 11:46 UTC, AntoineRelief commented on libs/shared/src/lib/models/draftRecord.model.ts
> +interface Version {
@LenaelleRelief 
cc @estelafs 
for file names, prefer to use this format:
"draft-record", than this one: "draftRecord"

2023-11-06 11:49 UTC, AntoineRelief commented on libs/shared/src/lib/components/form/form.component.ts
> +    const dialogRef = this.dialog.open(SelectDraftRecordModalComponent, {
@LenaelleRelief 
cc @estelafs 
invalid import
now, for modals, we prefer to use lazy loading import

2023-11-06 12:00 UTC, AntoineRelief commented on libs/shared/src/lib/components/select-draft-record-modal/graphql/queries.ts
> +      form {
@LenaelleRelief cc @estelafs 
note that when doing that you query the form once per draft record, so it's a loooot of duplications

2023-11-06 12:21 UTC, AntoineRelief commented on libs/shared/src/lib/components/form/form.component.html
> -  <shared-record-summary
@LenaelleRelief cc @estelafs 
I didn't ask to remove that
I'll revert it

2023-11-06 12:25 UTC, LenaelleL commented on libs/shared/src/lib/components/form/form.component.html
> -  <shared-record-summary
Sorry, I must have misunderstood !

2023-11-06 12:32 UTC, AntoineRelief requested changes
a few things that don't work as expected:
- in the draft record modal ( when previewing ) we don't see the pages
- I didn't check all in details, but I think some methods that were used to remove temporary records after saving ( for resource / resources questions ) were disabled -> to double check
- the possibility to see draft should also be visible in the modal when adding new records ( from a grid, for example ). It may need to refactor the code, so the button to open the draft is a component ( instead of being a button in the form.component as it is now ).
- when the draft is saved ( not as a draft, but as a record ), the draft is not removed. It should be

2023-11-06 21:11 UTC, estelafs commented
Done:

- Added the page tabs and navigations to the draft record modal (when previewing)
- Created the shared DraftRecordComponent to add the draft button also in the form and record modal (using the form-builder and the form-helper services for the common methods)
- Now when a draft is loaded and saved as a new record, the draft used is deleted
- I started updating the ResourceModalComponent and the survey utils.ts file to always create draft files instead of temporary (not finished)

2023-11-07 21:09 UTC, estelafs commented
Done: updated ResourceModalComponent and the survey utils.ts file to always create draft files instead of temporary records with the local storage

2023-11-09 10:32 UTC, merged

2023-11-09 10:33 UTC, AntoineRelief commented
@LenaelleRelief  @estelafs 
really good combined work 👏👏👏
that's a great new feature