feat/#AB#78673_Add-more-options-to-dashboard
ReliefApplications/ems-frontend pull request #2055
Opened 2023-11-08 17:25 UTC by TaiKamilla

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2023-11-16 08:39 UTC, AntoineRelief commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
> +    this.dashboardService.dashboard$.subscribe((dashboard) => {
@TaiKamilla 
I think you overcomplexified the code by putting a logic there to subscribe to current dashboard

2023-11-16 08:41 UTC, AntoineRelief commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
> +      gridOptions: this.fb.group({
@TaiKamilla 
there, you should have put a logic to detect if yes or no we should add the gridOptions control

2023-11-16 08:50 UTC, TaiKamilla commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
> +      gridOptions: this.fb.group({
oh, I see
I was planning to do so at the begging
But looks like I forgot to add a TODO
🥲

2023-11-16 08:51 UTC, TaiKamilla commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
> +    this.dashboardService.dashboard$.subscribe((dashboard) => {
I did not see a simpler way
What did I miss?

2023-11-16 08:56 UTC, unai-reliefapp requested changes

2023-11-16 08:56 UTC, unai-reliefapp commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.ts
> +        minCols: this.fb.control(this.dashboard?.gridOptions?.minCols ?? 8),
Hi @TaiKamilla , I'll recommend to set this loose fixed values(8, 200,  10) as const properties in a separate file and use them both here and when creating the [grid component](https://github.com/ReliefApplications/ems-frontend/blob/beta/libs/shared/src/lib/components/widget-grid/widget-grid.component.ts#L32-L35) in order to avoid mismatches of values between different fixed type values because of not having a single source of truth

KR, Unai

2023-11-16 08:56 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
> +      margin: this.gridOptions?.margin ?? 10,
Same as previous comment 😄

2023-11-16 08:56 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
> +      fixedRowHeight: this.gridOptions?.fixedRowHeight ?? 200,
Same as previous comment 😄

2023-11-16 08:56 UTC, unai-reliefapp commented on libs/shared/src/lib/services/dashboard/dashboard.service.ts
> +      .subscribe(() => {
Error handler and checker in case response is not valid or error is thrown?
@AntoineRelief

2023-11-16 08:56 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widget-grid/widget-grid.component.ts
> +    this.dashboardService.dashboard$.subscribe((dashboard) => {
Remember to add subscription teardown logic(like the takeUntil) to avoid memory leak issues you naughty, naughty boy

2023-11-16 09:20 UTC, AntoineRelief commented
@TaiKamilla 
I fixed a few things
A few additional comments:

- Changes will only work in back-office, so also do it in front-office ( apply grid options using input )
- set minimum / maximum / possibility to go back to default values for the inputs:
![Capture d’écran 2023-11-16 à 10 14 02](https://github.com/ReliefApplications/ems-frontend/assets/50317271/65095d12-acb9-412f-a9e1-6105206eef4a)
- number of columns: between 4 & 24. Default is 8
- row height: minimum 50, default 200, no max
- margin: default 10, minimum 0, no max
- outer margin: just remove it, we will never use it ( I was thinking about the margin around the dashboard, not the one around all the widgets )
- add a suffix in the inputs, with possibility to revert to default (it should have a tooltip to tell so)
- there is an issue when changing the number of columns. I think I can't go below 8 ( the grid always show 8 ) & if I set more than 8, I can't put multiple widgets on the same line ( it always think the number of cols is 8 ). See video below:

2023-11-17 15:55 UTC, AntoineRelief commented
@TaiKamilla 
I'm converting it to draft
please change it back to ready when changes are done

2023-11-20 17:10 UTC, TaiKamilla commented
@AntoineRelief I did all the suggested changes, the only thing I am not happy with is the initialization and the declaration of the default values of the gridOptions like @unai-reliefapp mentioned
Currently is done by libs/shared/src/lib/components/widget-grid/widget-grid.component.ts but I don't think it should be there.
Should it be moved to the dashboard service?
There is also a grid service

I don't know what to do about that, any feedback?

2023-11-21 09:11 UTC, AntoineRelief commented on apps/back-office/src/app/components/view-settings-modal/view-settings-modal.component.html
> +        <ui-tab *ngIf="data.page?.type !== 'form'">
@TaiKamilla 
this test was invalid
indeed, it would also appear for a workflow

2023-11-21 09:25 UTC, merged

2023-11-21 09:28 UTC, AntoineRelief commented
@TaiKamilla 
most of it working, but a few things were not correct:
- the test to determine if the options should be shown. Easier to use if dashboard exists or not
- some required jsdoc comments were missing

I also changed some logic for the columns. Indeed, if you had a grid with widgets bigger than the limits, it would have been hard to resize them
I changed it so the limit is not applied directly, if the widgets are bigger than the set limit ( so user can resize them ). When all widgets are resized, the value should be applied