feat: started to add possibility to select an aggregation in tinymce …
ReliefApplications/ems-frontend pull request #2059
Opened 2023-11-09 20:02 UTC by RenzoPrats

…editor

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2023-11-15 10:27 UTC, MwanPygmay reviewed
- Tested, indeed works, but options available for now are very restricted (the aggregation just appears in the propositions, but you cannot get data from it).
- Added mapping for the new aggregation

2023-11-16 09:14 UTC, unai-reliefapp requested changes

2023-11-16 09:14 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/common/aggregation-settings/aggregation-settings.component.ts
> +      ?.valueChanges.subscribe((val: any) => {
```suggestion
      ?.valueChanges.pipe(takeUntil(this.destroy$)).subscribe((val: any) => {
```

2023-11-16 09:14 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/common/aggregation-settings/aggregation-settings.component.ts
> +          this.selectedAggregation = value;
If value type set from the modal is string(aggregation id) we still have an aggregation selected in the formgroup, but the `selectedAggregation` property could be undefined, has this been thoroughly checked?(on canceling, saving and opening again modal, on switching tabs, on close and openning settings etc etc)

e.g. `editAggregation` method won't work as it's checking `if (value && this.selectedAggregation)` and if the first added aggregation only sets the id like it's done here, `selectedAggregation` is not updated and even if an aggregation id is set, cannot be edited

KR, Unai

2023-11-16 09:14 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/editor-settings/editor-settings.component.ts
> +      ?.valueChanges.subscribe((val: any) => {
```suggestion
      ?.valueChanges.pipe(takeUntil(this.destroy$)).subscribe((val: any) => {
```

2023-12-13 17:17 UTC, AntoineRelief commented
@RenzoPrats @unai-reliefapp @MwanPygmay 
I will need to close this one, as it won't work
my bad for this one, I didn't provided enough information in the ticket

I was expecting to have the possibility to put many aggregations, like that:

{{aggregation(id)[0].count}} for example, which should be transformed when loading the widget
this last part is missing

Also, one aggregation per widget is not enough, and it should be possible to use more than one
In addition, I'll remove the possibility to do it in summary cards, as I think it will generate conflicts

2023-12-13 17:17 UTC, closed without merging