Ab#79314 add filters tooltips
ReliefApplications/ems-frontend pull request #2088
Opened 2023-11-21 14:57 UTC by MwanPygmay

# Description

Add suggestions to filters as tooltips (see screenshots). 
Following fields are supported: _numeric_, _text_, _time_, _date_. 
- **numeric**: provide min and max value.
- **text**: provide five most common examples.
- **time**: provide min and max date.
- **date**: provide min and max date.

They should be supported everywhere filters are used: if data can not be acquired, check for a missing resource id, this is the most probable error source.
Time could not be tested as it has no special status in the filters.

## Useful links

-[ Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/79314/)
- [Please insert link to back-end branch if any](https://github.com/ReliefApplications/ems-backend/pull/837)
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Created four fields from above types. Tried to go everywhere filters are used (see places where a resourceId was provided), and checked if tooltip could indeed be acquired.

## Screenshots

![Screenshot from 2023-11-21 15-42-26](https://github.com/ReliefApplications/ems-frontend/assets/59645813/22f0128b-75e8-49d3-92ce-a0bfbfaa14b2)
![Screenshot from 2023-11-21 15-42-20
![Screenshot from 2023-11-21 15-42-22](https://github.com/ReliefApplications/ems-frontend/assets/59645813/361949d8-bd68-44a7-b8a2-bf7a46ca4437)
](https://github.com/ReliefApplications/ems-frontend/assets/59645813/34036367-4bfd-425d-a6ee-9ca5c9afc80a)
![Screenshot from 2023-11-21 15-42-23](https://github.com/ReliefApplications/ems-frontend/assets/59645813/e425b909-dfd1-4398-b5ce-1b5f097f8111)

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2023-11-21 21:26 UTC, estelafs requested changes
I did some updates:
- Updated translations where wrong key was used and spaces missing
- Updated incomplete code to work for time fields

@MwanPygmay the date questions type is not working, the request is never sent and we don't have a tooltiṕ, please check. 

Also, @AntoineRelief Should all scalar fields have tooltips, even those that are not related to questions such as "createdBy - name"? At the moment the backend doens't return values for these kind of fields, should we add in the frontend a check to disable the tooltip and don't query the hint for these fields or add hint to all of them?

2023-11-22 08:43 UTC, MwanPygmay commented
> I did some updates:
> 
>     * Updated translations where wrong key was used and spaces missing
> 
>     * Updated incomplete code to work for time fields
> 
> 
> @MwanPygmay the date questions type is not working, the request is never sent and we don't have a tooltiṕ, please check.
> 
> Also, @AntoineRelief Should all scalar fields have tooltips, even those that are not related to questions such as "createdBy - name"? At the moment the backend doens't return values for these kind of fields, should we add in the frontend a check to disable the tooltip and don't query the hint for these fields or add hint to all of them?

Yes, will rework on that, thanks for the translation! Mmmmh weird for the date questions, they work on my side, are you sure this is not a time question problem?

2023-11-22 12:26 UTC, estelafs commented
> EDIT: Tested, refactored back-end. Every type from numeric, text, date and time is working. The only thing is that as time is using text editor, it uses 'Examples from datasource' instead of 'Values from datasource are between', but I think the correct fix would be to have a time editor inside of the filters.

@MwanPygmay  Huum, that's weird. Here's a gif of my problem with the date type (is really a single-input question of type date): is working for the text questions, request sent etc, but when I try with the date question nothing happens, just the date format tooltip is displayed

[date.webm](https://github.com/ReliefApplications/ems-frontend/assets/28535394/b7beae36-e4ee-42f3-8512-45985b73a33d)

2023-11-23 08:56 UTC, MwanPygmay commented
> > EDIT: Tested, refactored back-end. Every type from numeric, text, date and time is working. The only thing is that as time is using text editor, it uses 'Examples from datasource' instead of 'Values from datasource are between', but I think the correct fix would be to have a time editor inside of the filters.
> 
> @MwanPygmay Huum, that's weird. Here's a gif of my problem with the date type (is really a single-input question of type date): is working for the text questions, request sent etc, but when I try with the date question nothing happens, just the date format tooltip is displayed
> date.webm

Indeed there is a date template in the query builder that did not get its tooltip, latest commits should fix it @estelafs

2023-11-23 14:17 UTC, estelafs approved these changes

2026-06-20 10:51 UTC, closed without merging