add lastComponentEmitter variable
ReliefApplications/ems-frontend pull request #2237
Opened 2024-01-03 12:45 UTC by MwanPygmay

# Description

- Add _lastComponentEmitter_ var to check what was the last emitter of the filter change. When emitting a new value, the component is changed.
- Only reload if the component is not at the origin of the change.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/82564/)

## Type of change

- [x] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

http://localhost:4200/applications/63d7e5b7c7dee63f57e97dae/dashboard/6594253530c3c58403c02dae

## Screenshots

No visual change.

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-03 15:17 UTC, unai-reliefapp requested changes

2024-01-03 15:17 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/summary-card/summary-card-item-content/summary-card-item-content.component.ts
> +      this.contextService.lastComponentEmitter = this.parent.parent;
```suggestion
      this.contextService.lastComponentEmitter = this.parent?.parent;
```
If parent is optional we should check property just in case 😉

2024-01-03 15:27 UTC, estelafs approved these changes

2024-01-03 16:12 UTC, unai-reliefapp approved these changes

2024-01-04 11:17 UTC, AntoineRelief commented
@unai-reliefapp @MwanPygmay @estelafs 
I don't agree with the proposed solution
I'll close the PR and put back the ticket in progress, editing the proposed solution

The issue is that the widget does not need to reload because it does not rely on the dashboard filter
All the aggregations used in the don't use {{filter.<etc>}}, which is why the widget can stay as it is

2024-01-04 11:17 UTC, closed without merging

2024-01-04 11:29 UTC, MwanPygmay commented
@AntoineRelief yes but in the case where the text editor depends on the contextual filter, when clicking on it it will still trigger its own reload, which feels unlogical to me.

2024-01-04 11:43 UTC, AntoineRelief commented
@MwanPygmay 
I put more explanation about that in the ticket