Ab#83681 support for context in front office without templates
ReliefApplications/ems-frontend pull request #2295
Opened 2024-01-17 16:30 UTC by MwanPygmay

# Description

Add support for context data by url in front-office (even when no template exists). Created a query to get a temporary dashboard that is a copy of the default one, with added context. Query is executed if no template can be found.
If the data does not exist, we create the temporary dashboard

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/83681)
- [Please insert link to back-end branch if any](https://github.com/ReliefApplications/ems-backend/pull/946)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

Created a dashboard with context datasource, two widgets (one for ref data, the other for resource), added some templates (in my case bulbasaur and rattata were templates), and tested. When template exists, it is loaded, if it does not exist we still take into account the context data.

## Screenshots

![contextDataInFront](https://github.com/ReliefApplications/ems-frontend/assets/59645813/45ef265d-1fef-435d-b908-e3523267e56e)

# Checklist:

( * == Mandatory ) 

- [x] * I have set myself as assignee of the pull request
- [x] * My code follows the style guidelines of this project
- [x] * Linting does not generate new warnings
- [x] * I have performed a self-review of my own code
- [x] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [x] * I have commented my code, particularly in hard-to-understand areas
- [x] * I have put JSDoc comment in all required places
- [x] * My changes generate no new warnings
- [x] * I have included screenshots describing my changes if relevant
- [x] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-01-18 12:37 UTC, AntoineRelief commented
@matheus-relief 
for review
I'm not 100% sure we need to build a new query for that in the back-end
if we query the dashboard, perhaps we could find an easier way to fetch the context?

2024-01-19 04:07 UTC, matheus-relief commented
@AntoineRelief I refactored it a bit. I removed the new query (and another one that we used for creating new contextualized dashboards). Instead, now we can directly query the dashboard with the record id for the context. If there is one it'll be returned, and if there isn't a new one will be created and returned.

2024-01-19 12:09 UTC, AntoineRelief commented
@matheus-relief 
one question about your last comment
if you're a front office user, does it mean it will create a new dashboard as well?

2024-01-21 00:30 UTC, matheus-relief commented
@MwanPygmay @AntoineRelief Addressed both your comments. Now it only creates a new template if you're on the backoffice. 

The JSDoc I left on the dashboard query sums it up pretty well I think

```
/** Arguments for the dashboard query */
type DashboardArgs = {
  id: string | Types.ObjectId;
  contextEl: any;
  createIfMissing: boolean;
};

/**
 * Throw GraphQL error if not logged.
 * Returns the dashboard by id if no contextEl is provided.
 * If contextEl is provided and its template already exists, returns the template.
 * If contextEl is provided and its template does not exist:
 *   - if createIfMissing is false, returns the main dashboard with the relevant context
 *   - if createIfMissing is true, creates a new template for the element and returns it (if user has permissions)
 */
```

2024-01-24 15:15 UTC, RenzoPrats commented
@matheus-relief @MwanPygmay I found some issues:

- When change the select of the context it does not update the dashboard
- Some items of the context returns an error

![Peek 24-01-2024 12-06](https://github.com/ReliefApplications/ems-frontend/assets/56398308/1c37217a-8620-48c2-9a5d-1aa5162be989)

When we enter in a context edit it, go to another and then come back it seems that it reset
![Peek 24-01-2024 12-07](https://github.com/ReliefApplications/ems-frontend/assets/56398308/cacc312f-bb1f-4a7f-9052-049d9f97c5ab)

2024-01-24 15:29 UTC, RenzoPrats requested changes
@matheus-relief @MwanPygmay I found some issues:

- When change the select of the context it does not update the dashboard
- Some items of the context returns an error

![Peek 24-01-2024 12-06](https://github.com/ReliefApplications/ems-frontend/assets/56398308/1c37217a-8620-48c2-9a5d-1aa5162be989)

When we enter in a context edit it, go to another and then come back it seems that it reset
![Peek 24-01-2024 12-07](https://github.com/ReliefApplications/ems-frontend/assets/56398308/cacc312f-bb1f-4a7f-9052-049d9f97c5ab)

2024-01-24 15:41 UTC, MwanPygmay commented
@RenzoPrats the ticket is about changes in front-office, I think the tests you are doing are done from back-office, if I am not mistaken. If you found a bug in back-office, please put it in oort-bug channel, and we will address it in a new ticket!

2024-01-24 17:23 UTC, AntoineRelief commented
@MwanPygmay 
based on last changes from @matheus-relief I think both are now related

2024-01-24 17:27 UTC, RenzoPrats commented
@MwanPygmay that's true, sorry I thought could be about the context of this ticket. So in the front office the issue that I can see is: 
Default dashboard
![Captura de tela de 2024-01-24 14-19-45](https://github.com/ReliefApplications/ems-frontend/assets/56398308/95d3ae43-1601-42c6-a198-91097fcc7054)
Configure a dashboard with context in backoffice
![Captura de tela de 2024-01-24 14-20-27](https://github.com/ReliefApplications/ems-frontend/assets/56398308/77ddd2e3-21cf-4c3a-9cab-fac99708ddb8)
When navigate to frontoffice in the default dashboard we can see the chart I configured before but without data:  
![Captura de tela de 2024-01-24 14-22-57](https://github.com/ReliefApplications/ems-frontend/assets/56398308/de285b55-d0bd-43e3-bc48-3273fa2e1089)
and if we go to the one with context it looks like the default one of backoffice.
![Captura de tela de 2024-01-24 14-23-10](https://github.com/ReliefApplications/ems-frontend/assets/56398308/558c9b69-1089-436d-afb5-9733f946484f)

I'm not sure if this is scope of this ticket, the issue about see the default when we navigate to a dashboard context that is not created yet is working.

2024-01-25 03:59 UTC, matheus-relief commented
Thanks @RenzoPrats!! I fixed a couple of the problems:

* ~~When change the select of the context it does not update the dashboard~~
* ~~When we enter in a context edit it, go to another and then come back it seems that it reset: The issue there was we were editing the main dashboard instead of the templates~~

This one I could not replicate:

> Some items of the context returns an error

I even tried the same refData and config but no luck, and I also looked and we don't seem to be used .replace anywhere in the back on the dashboard query or field resolvers, so I'm not sure where the error is coming from... Can you share the error you were getting?

This one I think it's just a side effect you the bug I fixed where you edited the wrong dashboard. 

> When navigate to frontoffice in the default dashboard we can see the chart I configured before but without data

2024-01-29 15:02 UTC, RenzoPrats approved these changes
Hi @matheus-relief, thanks for the repairs it's working fine, about the issue that I mentioned I found where it was happening in the code and fixed. it was happening when we move to a dashboard with context and create some widget, when we navigate to another id and come back wasn't possible to get the settings of the widget  causing errors. Now I think it's working fine.

2024-01-29 15:07 UTC, AntoineRelief commented on apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
> +            ...omit(this.gridOptions, 'gridType'), // Prevent issue when gridType was not set
@RenzoPrats 
why removing this?

2024-01-29 15:07 UTC, AntoineRelief commented on apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
> -          this.contextService.filterPosition.next({
@RenzoPrats 
same there

2024-01-29 15:10 UTC, RenzoPrats commented on apps/back-office/src/app/dashboard/pages/dashboard/dashboard.component.ts
> -          this.contextService.filterPosition.next({
Sorry, I just saw it and I'm gonna fix, I think when I pressed ctrl+z I changed to the previous merge branch and caused issue.

2024-01-31 12:16 UTC, AntoineRelief commented
missing:
- not anymore a notification when creating a new template

2024-01-31 14:46 UTC, AntoineRelief commented
@MwanPygmay @matheus-relief @RenzoPrats 
now seems to work fine!

there was a few things missing:
- context not correctly passed to context service
- widgets were immutable in front-office in some cases
- web-widgets app not updated ( but that, I can't blame you for it )

2024-01-31 14:47 UTC, merged

2024-01-31 16:24 UTC, matheus-relief commented on apps/back-office/src/environments/environment.ts
> +  strictDiscoveryDocumentValidation: false,
Was did committed on purpose?