AB#86500_add_valid_json_validator
ReliefApplications/ems-frontend pull request #2409
Opened 2024-02-22 09:34 UTC by MwanPygmay

# Description

Add validator to check for invalid JSON value.
Add alert to warn user if the value is invalid.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/86500)

## Type of change

Please delete options that are not relevant.
- [ ] Improvement (refactor or addition to existing functionality)

# How Has This Been Tested?

tested in summary card, tried with empty json, normal and with errors.

## Screenshots

![validJsonValidator](https://github.com/ReliefApplications/ems-frontend/assets/59645813/970b5dd5-8b1d-48c2-b7f1-cbccd270043c)

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2024-02-23 09:28 UTC, unai-reliefapp reviewed
Hi @MwanPygmay , maybe set the control validator inside the graphql variables component in order to keep validator and related control tight coupled?
We want the validjson feature in the graphql variables component always right?
Place it there and we don't have to go control by control to set the validator

What do you think?
KR, Unai

cc @AntoineRelief

2024-02-23 10:44 UTC, unai-reliefapp requested changes

2024-02-23 10:44 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
> +    this.control.setValidators(validJson());
```suggestion
    this.control.setValidators(validJson());
    this.control.updateValueAndValidity();
```
https://angular.io/api/forms/AbstractControl#setValidators
Also set validators would replace any other validator set in the control, maybe would be better to use the `addValidators()` method?

KR, Unai

2024-02-23 10:44 UTC, MwanPygmay commented
@unai-reliefapp fully agree with you, made a commit to remove validators from parents and instead setting it from the graphql-mapping component onInit.

2024-02-23 10:53 UTC, unai-reliefapp requested changes

2024-02-23 10:53 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
> +  <ui-alert variant="danger" *ngIf="!control.valid">{{
If the control is invalid for any other reason than the `invalidJson: true` this message would also be triggered 😅 
Maybe the `*ngIf` check should be more strict, if no valid and errors contains `invalidJson` 

Besides that if you already check it again and still works fine, approved 👍

2024-02-23 13:17 UTC, MwanPygmay commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.html
> +  <ui-alert variant="danger" *ngIf="!control.valid">{{
yup changed it should be all good

2024-02-23 13:34 UTC, unai-reliefapp approved these changes

2024-02-26 09:11 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
> +    this.control.addValidators(validJson());
@MwanPygmay @unai-reliefapp 
there is one issue there

I don't think it would affect the performance, but it is not quite clean

indeed, anytime you would enter the component, you would add the validator to the control, so it can end up with a control having multiple times the same validator attached to it

you should better check if the validator is already attached to the control before adding it

2024-02-26 09:16 UTC, unai-reliefapp commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
> +    this.control.addValidators(validJson());
According to Angular that's not a problem
![image](https://github.com/ReliefApplications/ems-frontend/assets/123092672/4f427801-1e9f-4193-8e01-7934e5eb2389)
https://angular.io/api/forms/AbstractControl#addValidators

2024-02-26 10:58 UTC, AntoineRelief commented on libs/shared/src/lib/components/widgets/common/graphql-variables-mapping/graphql-variables-mapping.component.ts
> +    this.control.addValidators(validJson());
in that case, i'll merge it, thanks @unai-reliefapp !

2024-02-26 11:07 UTC, merged