Fix/ab#86920 tooltip prevents click events
ReliefApplications/ems-frontend pull request #2418
Opened 2024-02-28 08:55 UTC by NathanHGit

# Description

I removed the pointer events of the tooltip to prevent it from blocking click events. Additionally, I added some code to move the tooltip to the left if it overflows at the bottom of the screen.

## Useful links

- [Please insert link to ticket](https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/86920/)

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

I created a dashboard composed of multiple widgets. I set grid type to `verticalFixed` and ensured that the chart widget was close to the bottom by modifying row heights. I verified the behavior of the tooltip.

## Screenshots

![peek](https://github.com/ReliefApplications/ems-frontend/assets/65243509/67dcdc14-a85f-4328-b111-bbdbdcd3ddf8)

# Checklist:

( * == Mandatory ) 

- [X] * I have set myself as assignee of the pull request
- [X] * My code follows the style guidelines of this project
- [X] * Linting does not generate new warnings
- [X] * I have performed a self-review of my own code
- [X] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [X] * I have commented my code, particularly in hard-to-understand areas
- [X] * I have put JSDoc comment in all required places
- [X] * My changes generate no new warnings
- [X] * I have included screenshots describing my changes if relevant
- [X] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2024-02-29 08:18 UTC, AntoineRelief commented
to be done

check if overlay ( like in the menu directive can't be used )

2024-02-29 08:54 UTC, AntoineRelief commented
@MwanPygmay 
about this one, perhaps we can do the same logic than in the menu.directive

meaning that we would use the cdk overlay to display the tooltip
the overlay would permit to set conditional positions ( this is what we are doing for the menu ) meaning that if the element can't display at bottom ( not enough space, then it will try to display it somewhere else

2024-03-06 09:23 UTC, MwanPygmay commented
EDIT: 
- Change to cdk overlay.
- Remove most of the tooltip component to use it in the directive: user story will probably be broken.
- Remove the tooltip position directive to change it for an input in the tooltip directive.
![tooltipCDK](https://github.com/ReliefApplications/ems-frontend/assets/59645813/8f69f561-a5a2-40f4-9058-077444cbaeb5)

2024-03-11 09:23 UTC, AntoineRelief commented
@MwanPygmay 

putting back the ticket in draft
In general, it works better, but a few things are broken

a few things I noted:
- there is no more space between the element that triggers the tooltip and the tooltip. See the difference:
| New | Old |
|--------|--------|
| <img width="175" alt="Capture d’écran 2024-03-11 à 10 18 10" src="https://github.com/ReliefApplications/ems-frontend/assets/50317271/36137a7f-b6a0-4622-b9ba-d5ccf263c141"> | <img width="270" alt="Capture d’écran 2024-03-11 à 10 18 05" src="https://github.com/ReliefApplications/ems-frontend/assets/50317271/08849963-946a-485f-ae3d-fdbd1b36423c"> |

- multi line tooltip not working ( example in grid widget actions )
| New | Old |
|--------|--------|
| <img width="1179" alt="Capture d’écran 2024-03-11 à 10 19 16" src="https://github.com/ReliefApplications/ems-frontend/assets/50317271/268515a5-ec41-4bf5-90c1-f0c4ddee64f6"> | <img width="493" alt="Capture d’écran 2024-03-11 à 10 19 10" src="https://github.com/ReliefApplications/ems-frontend/assets/50317271/1bbc9130-2e62-4274-9259-d7d6f85dd646"> | 

- I prefer to use the old name, uiTooltipPosition than preferredPosition, if you can change that. It can remain an attribute, but it should be clear in the name that this is for the tooltip.

2024-03-11 14:43 UTC, unai-reliefapp commented
> @MwanPygmay
> 
> putting back the ticket in draft In general, it works better, but a few things are broken
> 
> a few things I noted:
> 
> * there is no more space between the element that triggers the tooltip and the tooltip. See the difference:
>   | New | Old |
>   |--------|--------|
>   | <img alt="Capture d’écran 2024-03-11 à 10 18 10" width="175" src="https://private-user-images.githubusercontent.com/50317271/311649213-36137a7f-b6a0-4622-b9ba-d5ccf263c141.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjgzNTcsIm5iZiI6MTcxMDE2ODA1NywicGF0aCI6Ii81MDMxNzI3MS8zMTE2NDkyMTMtMzYxMzdhN2YtYjZhMC00NjIyLWI5YmEtZDVjY2YyNjNjMTQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMjk1NTZiODA0MmNhMzAxODczZDMyOTk0OTY0M2ZhNzkyNGI5MGNiZDljODM0ZmE5OGQ4MzNjZGMwYzQzZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1mkbRwnMfLSJp2hFIwuzGNrk69ZsQlcwVQn9MLrSwI"> | <img alt="Capture d’écran 2024-03-11 à 10 18 05" width="270" src="https://private-user-images.githubusercontent.com/50317271/311649264-08849963-946a-485f-ae3d-fdbd1b36423c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjgzNTcsIm5iZiI6MTcxMDE2ODA1NywicGF0aCI6Ii81MDMxNzI3MS8zMTE2NDkyNjQtMDg4NDk5NjMtOTQ2YS00ODVmLWFlM2QtZmRiZDFiMzY0MjNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg0ZjllNTliOGU2Njk3ZWI2ZjhhNGUzNjBkN2E0ZDM3MTQwNDhjMzA4ODVmYjIwMGIwMzFiNzljMjRhOGQyYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2Za_wSedDPLWpPxEKDUilmsxInsb54Zn8wiU0iXfy0Y"> |
> * multi line tooltip not working ( example in grid widget actions )
>   | New | Old |
>   |--------|--------|
>   | <img alt="Capture d’écran 2024-03-11 à 10 19 16" width="1179" src="https://private-user-images.githubusercontent.com/50317271/311649572-268515a5-ec41-4bf5-90c1-f0c4ddee64f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjgzNTcsIm5iZiI6MTcxMDE2ODA1NywicGF0aCI6Ii81MDMxNzI3MS8zMTE2NDk1NzItMjY4NTE1YTUtZWM0MS00YmY1LTkwYzEtZjBjNGRkZWU2NGY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcxMGQyZjJiODY5NDAwMGM0MWQ4MmIzNWQ5NjM0ODZmOTRkMzZmMmRjMDQwNGVhODY5ZDljZjA4MmIzMmY0Y2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._Xxnv1tOpPDIHohJ1OPY_llY8iBsjcoFRwl6R-SZvjs"> | <img alt="Capture d’écran 2024-03-11 à 10 19 10" width="493" src="https://private-user-images.githubusercontent.com/50317271/311649497-1bbc9130-2e62-4274-9259-d7d6f85dd646.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNjgzNTcsIm5iZiI6MTcxMDE2ODA1NywicGF0aCI6Ii81MDMxNzI3MS8zMTE2NDk0OTctMWJiYzkxMzAtMmU2Mi00Mjc0LTkyNTktZDdkNmY4NWRkNjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE0NDA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIxNjZhMjRmOTMyYjZlYjJhMzc1YmM1ZmNhMzNiM2IwNDRiNzExMmIzODliZGUyNDVjZDgyMmRiNjEzYzc4MmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sKfjo7vOSQO8eWU84E4V6stWSnZMGS_2wOsMQklQfXg"> |
> * I prefer to use the old name, uiTooltipPosition than preferredPosition, if you can change that. It can remain an attribute, but it should be clear in the name that this is for the tooltip.

- Fix space between element and tooltip adding offset to Y axis as needed for top or bottom tooltips
![image](https://github.com/ReliefApplications/ems-frontend/assets/123092672/ef111fab-e2cd-4f59-9686-9bc47029432c)
- Fix multi line issue for tooltips adding block display type
![image](https://github.com/ReliefApplications/ems-frontend/assets/123092672/574304b9-ee8a-4542-a1ee-49a8ee2e405c)
- Change name to uiTooltipPosition
- Add type for uiTooltipPosition
- Fix error of leaving "rubbish" elements in the DOM when adding/removing tooltip by creating/removing overlayref as needed only
![image](https://github.com/ReliefApplications/ems-frontend/assets/123092672/c4f66caf-379f-40a2-84f0-7bc0c8d86461)

cc @AntoineRelief

2024-03-11 15:25 UTC, AntoineRelief commented
@unai-reliefapp 
It should look the same as before

2024-03-11 15:26 UTC, unai-reliefapp requested changes

2024-03-11 15:26 UTC, unai-reliefapp commented on libs/ui/src/lib/tooltip/tooltip.component.html
> +  class="opacity-80 block transition-opacity delay-300 bg-gray-800 p-2 max-w-xs whitespace-pre-wrap text-xs text-gray-100 rounded-md z-[9999] break-words pointer-events-none"
```suggestion
  class="block transition-opacity delay-300 bg-gray-800 p-2 max-w-xs whitespace-pre-wrap text-xs text-gray-100 rounded-md z-[9999] break-words pointer-events-none"
```
To look same as before @AntoineRelief

2024-03-11 15:48 UTC, unai-reliefapp approved these changes

2024-03-12 08:35 UTC, merged