Email notifications next
ReliefApplications/ems-frontend pull request #2460
Opened 2024-03-25 14:43 UTC by AntoineRelief

# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Useful links

- Please insert link to ticket
- Please insert link to back-end branch if any
- Please insert any useful link ( documentation you used for example )

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Improvement (refactor or addition to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce.

- [ ] Test A
- [ ] Test B

## Screenshots

Please include screenshots of this change. If this issue is only back-end related, and does not involve any visual change of the platform, you can skip this part.

# Checklist:

( * == Mandatory ) 

- [ ] * I have set myself as assignee of the pull request
- [ ] * My code follows the style guidelines of this project
- [ ] * Linting does not generate new warnings
- [ ] * I have performed a self-review of my own code
- [ ] * I have put the ticket for review, adding the oort-frontend team to the list of reviewers
- [ ] * I have commented my code, particularly in hard-to-understand areas
- [ ] * I have put JSDoc comment in all required places
- [ ] * My changes generate no new warnings
- [ ] * I have included screenshots describing my changes if relevant
- [ ] * I have selected labels in the Pull Request, according to the changes with code brings
- [ ] I have made corresponding changes to the documentation ( if required )
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

# More explanation
https://www.loom.com/share/05a716d61b9744faaf51fb304c21d1e5?sid=f87cf896-582a-4f76-93ae-8ceed801b145

2024-04-17 03:27 UTC, HasnatL-Adapptlimited commented
Hi @AntoineRelief, @MwanPygmay, @matheus-relief 

Hope you're doing well!

These changes have been pushed:

## Data Changes
- Resource, Resources, CreatedBy nested fields, data persisting in preview pages and final email
- Operators populating correctly for resource and resources
- Field select now grouped and sorted correctly

## Style Fixes
- Dual List Implemented instead of click for field select
- Converted the landing page in to ui-tab view
- Search bar consistent with rest of app builder
- Modified the "Save and Proceed" button to Next
- Back button now uses ui-button
- Removed or use existing text from step 1 under email notification stepper page
- Added tool tips under the data set page for add and delete icons
- + Icon Moved out of the header
- Added the tooltip and text in distribution list page that reads "Type Email and hit ENTER to add
- Dropdown on email only provides email as option
- UI-checkbox used
- UI-Alert messaged moved to the top of page instead of at the bottom of distribution list page (step 4)

## To be delivered
- Distribution List Search on email notification page
- Send Seperate Email full functionality
- Createdby + lastupdatedby persiting in final email
- Replacing NG-Select with ui-select-menu on dataset select
- Replacing tabs with UI-tabs for dataset page

2024-04-18 08:16 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 
thanks Hasnat!
I think Matthis was planning to have a look today

2024-04-23 02:59 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 
In last commit, I reverted changes made on tooltip, as it was breaking the code

If you need them, please put them back, making sure the code can still build
also, I'm not sure about these changes and why they were done, so if we need them again, please put more explanation in a comment

2024-04-23 10:34 UTC, HasnatL-Adapptlimited commented
> @HasnatL-Adapptlimited In last commit, I reverted changes made on tooltip, as it was breaking the code
> 
> If you need them, please put them back, making sure the code can still build also, I'm not sure about these changes and why they were done, so if we need them again, please put more explanation in a comment

Tested on both chrome and firefox, tooltips seems to be working fine with revert, thank you

2024-04-23 13:47 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

FYI, I merged the last version of the 2.x.x branch in both front-office & back-office, so I could do another deployment on our UAT environment, and it's a good practice to keep the base branch up to date

please note that I didn't find any issue while doing so, but you may need to pull the branch before pushing any new commit

2024-04-23 13:51 UTC, HasnatL-Adapptlimited commented
> @HasnatL-Adapptlimited
> 
> FYI, I merged the last version of the 2.x.x branch in both front-office & back-office, so I could do another deployment on our UAT environment, and it's a good practice to keep the base branch up to date
> 
> please note that I didn't find any issue while doing so, but you may need to pull the branch before pushing any new commit

Hey @AntoineRelief, Yes thats fine, I saw and rebased the new fixes ontop of these changes, I will have another PR raised by the EOD with notes for the frontend and backend, thank you,

**Question:**
Would it be better if I raise and accept and merge the PR into this branch? or just raise the pr for each new bug fix?

2024-04-23 13:55 UTC, AntoineRelief commented
> > @HasnatL-Adapptlimited
> > FYI, I merged the last version of the 2.x.x branch in both front-office & back-office, so I could do another deployment on our UAT environment, and it's a good practice to keep the base branch up to date
> > please note that I didn't find any issue while doing so, but you may need to pull the branch before pushing any new commit
> 
> Hey @AntoineRelief, Yes thats fine, I saw and rebased the new fixes ontop of these changes, I will have another PR raised by the EOD with notes for the frontend and backend, thank you,
> 
> **Question:** Would it be better if I raise, and merge the PR into this branch? or just raise the pr for each new bug fix?

@HasnatL-Adapptlimited 

I think you can keep one PR per bug, so we can better track it

2024-04-23 14:18 UTC, Matthis-M-ReliefApps commented
Hi @HasnatL-Adapptlimited,
I'm still working on the code review itself, but here are a few feedbacks on the functional side that I can already give:

High Priority:

1. On preview page, always show the distribution list and recipients, to avoid bad surprises for the users (in case it was modified by another user for example).
2. When body is filled, then emptied, the validator doesn't always trigger and we can proceed with empty body.
3. It is possible to create a block from a dataset, but not set the fields, so it wouldn't show anything. There should probably be a validator there, unless I'm mistaking?
4. Per my understanding, the "Style" and "Send separate email" are features planned for the next phase. I recommend indicating that those features are disabled so the users don't think it's a bug (maybe through a tooltip or text on hovering). This also applies to "Scheduled alert" feature and others I might be missing.

Normal Priority:

1. To get a more consistent UX, reuse the breadcrumbs as they are used in the roles settings page, also with the browser's back button working.

2024-04-23 15:06 UTC, HasnatL-Adapptlimited commented
> > > @HasnatL-Adapptlimited
> > > FYI, I merged the last version of the 2.x.x branch in both front-office & back-office, so I could do another deployment on our UAT environment, and it's a good practice to keep the base branch up to date
> > > please note that I didn't find any issue while doing so, but you may need to pull the branch before pushing any new commit
> > 
> > 
> > Hey @AntoineRelief, Yes thats fine, I saw and rebased the new fixes ontop of these changes, I will have another PR raised by the EOD with notes for the frontend and backend, thank you,
> > **Question:** Would it be better if I raise, and merge the PR into this branch? or just raise the pr for each new bug fix?
> 
> @HasnatL-Adapptlimited
> 
> I think you can keep one PR per bug, so we can better track it

For todays PR is it okay if we push 1 large PR with notes linking to each bug?
Then from tomorrow onwards we create atomic PR's for each bug?

2024-04-23 15:08 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

sure, that's fine for me

2024-04-23 15:18 UTC, Matthis-M-ReliefApps requested changes
Hi @HasnatL-Adapptlimited,
I finished this round of review of the frontend.
Sorry for the huge amount of comments but don't worry, 90% of them are very small and easy-to-fix issues.
Please check the "High Priorities" ones first, they could in my opinion be blockers for the deployment. Let me know if any of my comments is lacking clarity.
Also, my general recommendation for the next developments would be to use the app builder's existing components as often as possible. Sometimes it takes a bit more time to find the right structure to fit them in, but it would really reduce duplication, and make maintenance easier.
In any case, well played for all the work done on this big feature, we're getting closer to production!

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/ui/src/lib/alert/alert.component.ts
> +    setTimeout(() => {
### HIGH PRIORITY
Small but core change to the alert component. This was added to prevent memory leaks, it shouldn't be removed. Was it causing an issue with your PR?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on apps/back-office/src/index.html
> +    <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-bootstrap@latest/dist/all.css"></link>
### High Priority
Would it be possible to avoid linking in the html and instead import it in "libs/styles/src/lib/kendo/theme.scss"?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on apps/front-office/src/index.html
> +    <link rel="stylesheet" href="https://unpkg.com/@progress/kendo-theme-bootstrap@latest/dist/all.css"></link>
### High Priority
Would it be possible to avoid linking in the html and instead import it in "libs/styles/src/lib/kendo/theme.scss"?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on assets/Avatar.png
A global search in VScode didn't return any place where this image is used.
- If it's not used, could you remove it?
- If it's used, could you rename it in lowercase, so it follows the assets folder's convention, and also let me know where and how it is used?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on assets/EMS_logo.jpg
A global search in VScode didn't return any place where this image is used.
- If it's not used, could you remove it?
- If it's used, could you rename it in lowercase, so it follows the assets folder's convention, and also let me know where and how it is used?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on assets/WHO.png
A global search in VScode didn't return any place where this image is used.
- If it's not used, could you remove it?
- If it's used, could you rename it in lowercase, so it follows the assets folder's convention, and also let me know where and how it is used?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.html
> +    and cannot be properly displayed in the table for this form.
Translation is missing here

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.scss
> +}
### High Priority
(Because it affects many lines of code)
For testing, I removed this class, but the "delete" button with danger and primary classes was not showing any style difference before/after. I'm thinking you might've changed the components in the meantime. Could you double-check if all the css of this file is still needed?
Otherwise, please let me know if I'm mistaking, it could also be some cache shenanigans or whatever.
Also, a big part of this code is duplicated in some other css file too.

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
Would it be possible to reuse existing components instead of creating custom ones such as this?
For example, have a look at "libs/shared/src/lib/components/filter/filter-row/filter-row.component.html"
It would have a couple of benefits:
- Better visual consistency, example:
existing one from ABC:
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/b65ddc6a-9faf-49c5-8629-872c89df5ae1)
custom one:
![image](https://github.com/ReliefApplications/ems-frontend/assets/80319175/6e7fa832-64db-42df-9439-30be2b019735)
- Make maintenance way easier
- Improve code scalability

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.html
> +                                        <label>Number</label>
Missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.html
> +                                        <label>Unit</label>
Missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.html
> +            <button (click)="applyFilter()">Apply</button>
Missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
> +  ];
Missing translations for some texts displayed to the user

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
> +    return Array.from({ length: 90 }, (_, i) => i + 1);
Magic number here should be replaced by a constant with a clear name

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Seems like a week email validation, could it be improved? Best option would be to use Angular validators like we do elsewhere.

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/email-template/email-template.component.ts
> +    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
Seems like a weak email validation, could it be improved? Best option would be to use Angular validators like we do elsewhere.

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
> +      };
Is this empty object normal?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
> +          this.emailService.sendSeperateEmail()
Typo, should be replaced everywhere by "Separate"

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
> +            console.log('Email sent successfully:', response);
To remove

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
> +  }
A chunk of those two functions is identical, could be refactored maybe?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/components/ems-template/ems-template.component.ts
> +      this.emailService.datasetsForm?.value?.datasets?.forEach((data: any) => {
Didn't check in details, but in the same statement on line 314, "datasets?" is written with a capital "S". Could it be a typo?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.service.ts
> +  replaceUnderscores(userValue: string): string {
Name seems wrong since it's replacing by whitespaces and not underscores

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.service.ts
> +   * persisting the state of the boolean variable for sending separete emails
typo

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.service.ts
> +  setSeperateEmail(seperateEmail: boolean, index: number): void {
typo

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/create-dataset/create-dataset.component.html
> +            no data found
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/create-dataset/create-dataset.component.scss
Similar comment as on the other scss file. I'm quite sure a lot of lines are not needed in this one and could be removed

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.scss
Same comment as for the previous scss files, quite a lot of duplicated code that is probably not needed.

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/create-dataset/create-dataset.component.ts
> +    console.log('Final Response', finalResponse);
to remove

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/create-notification/create-notification.component.html
> +        Title already exists!
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/i18n/en.json
> +				"existing": "Or use existing",
Since distribution lists are not independent objects being shared between notifications, the naming of the option "Or use existing" seems ambiguous to me. Would it be possible to replace by "Or copy existing" or "Or import existing"?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.html
> +                        >
Could the tooltips be translated there?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/layout/layout.component.html
> +            class=" w-full">
missing placeholder and tooltip translations

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/layout/layout.component.html
> +            uiTooltip="Date fields filtered by within the last"
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/layout/layout.component.ts
> +    { value: '{{now.datetime}}', label: 'Date and Time' },
translate labels

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/layout/layout.component.ts
> +    console.log(bodyHtml);
remove

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/schedule-alert/schedule-alert.component.html
translations to review in this file once implementation continued

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
Please check tooltips translations in this file

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
> +    To proceed, please enter <strong *ngIf="recipients?.distributionListName?.length === 0 || recipients?.distributionListName?.trim() === '' "> a distribution list name</strong> <strong *ngIf="recip
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/steps/select-distribution/select-distribution.component.html
> +    <p (click)="showExistingDistributionList = !showExistingDistributionList" >Or Create New</p>
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/role-summary/role-resources/resource-access-filters/resource-access-filters.component.scss
Same comment as on other css files

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.ts
> +    console.log('Toggle is calling');
to remove (please do a search in the rest of the code too, I could've missed a few)

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.ts
> +        let uniquDistributionLists = Array.from(
typo?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.ts
> +            emailData.name = emailData.name + '_Clone';
I didn't double-check by running it in the app, but is it normal that you're writing both "_clone" and "_Clone"?

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.ts
> +        content: `Block 1 Content`,
maybe translation here too

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/email.component.ts
> +      content: 'Do you confirm the deletion of ' + data.name + ' ?',
missing translation

2024-04-23 15:18 UTC, Matthis-M-ReliefApps commented on libs/shared/src/lib/components/email/filter/filter.constant.ts
What's the reason for not reusing "libs/shared/src/lib/components/filter/filter.const.ts"? Could there be cases where we want to update one but not the other?

2024-04-25 12:45 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

In last commit:
- removed useless full import of kendo bootstrap. It was breaking some style, so I preferred to only import additional style for the kendo tabs
- replaced one UI element by a divider, to reuse existing UI elements

cc @morgang-adappt

2024-04-25 12:47 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

In last commit, prettify code ( html / scss )

cc @morgang-adappt

2024-04-25 14:02 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

In last commit, use chip to indicate legacy pages ( distribution lists & templates )

cc @morgang-adappt

2024-04-25 15:16 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

in last commit
some UI improvements

@morgang-adappt

2024-04-26 15:24 UTC, HasnatL-Adapptlimited commented on libs/shared/src/lib/components/email/components/dataset-filter/dataset-filter.component.ts
We will try to reuse in phase 2

2024-04-30 08:08 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 
in last commit:
- refactor create-notification component to remove duplicated css / duplicated code
- refactor create-notification component to better use angular forms API
- refactor create-notification component to hide email notifications type dropdown ( based on this feedback https://dev.azure.com/WHOHQ/EMSSAFE/_workitems/edit/90480 )

2024-04-30 08:31 UTC, AntoineRelief commented
@HasnatL-Adapptlimited 

In last commit:
- refactor schedule alert component, to avoid counter counter intuitive logic ( schedule_alert set to true to represent a case where it is false )

2024-06-21 13:15 UTC, merged